---
title: "Temas por Charlar"
subtitle: "Asunto: varios"
author: "Laboratorio de Programaci칩n SIG"
format:
  revealjs:
    theme: simple
    slide-number: true
    transition: fade
    incremental: true
    center: true
---

## Clase de Hoy: Instalaci칩n y uso b치sido del Software


- 1. Docker Desktop
- 2. Instalar nuestros contenedores
- 3. VSCode + Extensiones (dentro del nuestros contenerores)
- 4. Git + GitHub
- 5. Acceso a Jupyter Lab
- 6. Creaci칩n de archivos Quarto (*.qmd): HTML & PDF
- 7. OSGeo4W (QGIS) - QGIS + GEE (Pixi)
- 8. Chequeo ArcGIS Pro


---


## Contenido - Syllabus actual

- 1. Principios de Programaci칩n.
- 2. Fundamentos de Python.
- 3. Marcos de Datos.
- 4. Programaci칩n Orientada a Objetos.
- 5. Python y PostgreSQL.
- 6. Librer칤as Geoespaciales.
- 7. ArcGIS.

游녤 Necesitamos modificarlo.

---

## Contenido - Estructura

- 1. Exposiciones del Profesor.
    - Teor칤a.
    - Pr치ctica.
- 2. Trabajos en Grupo.
- 3. Exposiciones de los Estudiantes.
- 4. Lecturas.
- 5. Pr치cticas.
- 6. Trabajo Final.

游녤 Necesitamos concretarlo y asignar porcentajes.

---

## Propuestas de Estudiantes para el Curso

游꿢 Tienes la palabra.

---

## Enfoque Open Science

- Material presentado por profesor
    - Diapositivas
    - C칩digo
    - Teor칤a
    - Archivos de configuraci칩n
- Material de los estudiantes
- HTML, PDF
- GitHub

---

## Seminario **LatinGeo** al final del curso


- Organizado por GeoCorp y UNAL.
- Presentar trabajos finales.
- Presentar temas espec칤ficos.
- Abierto al p칰blico (en l칤nea).
- Formato Open Science.
- Puede contribuir a la nota final.
- Podemos traer invitados.

游꿢 **LatinGeo**: Python, R y Julia

---

## Temas para Proyecto Final

- 1. Geocomputaci칩n en la Nube.
- 2. Virtualizaci칩n.
- 3. Librer칤as Geo: Pipelines Composables.
- 4. Creaci칩n de Paquetes (R, Python, Julia).
- 5. Creaci칩n de Extensiones.
- 6. GitHub Actions.
- 7. DuckDB
- 8. GEE - GEEMAP
- 9. Temas aplicados
- 10. ...

---

## Paquetes o comandos faltantes en Dockerfile

- `apt-get update && apt-get install -y fonts-symbola`
- Julia: `FileIO`, `ImageIO`
- Opcion B: QGIS OSGeo4W  y QGIS para correr el plugin GEE (archivo 03-guia_instalacion_B_qgis.qmd)
- Actualizar c칩digo en la gu칤a 02-A (usuario y clave y poner {} a todos menos a Julia)
- Quitar los n칰meros `### 1.`  en 03-B
- Actualizar 04-arcgis (est치 incompleto)
- Rscript -e "install.packages('webshot2')" (capturar pantalla en html dinamico para pdf)
- Dependencia de sistema para capturas (acompa침a al anterior)
- pip3 install selenium
- Gu칤a B (arreglar nivel de subt칤tulos)
- Semana 3 y 4: Proyecciones con R (Sillabus)
- BD PostGIS (5 y 6)