# Adicionales Sobre Python

## Versiones instaladas del software

Para verificar las versiones instaladas, puede ejecutar `pip3 list` en la terminal. Las versiones instaladas deben coincidir con la siguiente tabla:

| Software | Tipo | Versión | Comando (desde terminal) | Comando (desde Python) |
|:-|:--|:-|:----|:------|
| `Python` | Lenguaje | 3.12.3 | `python3 --version` | `import sys; sys.version` |
| `pip` | Gestor de paquetes | 24.0 | `pip3 --version` | `import pip; pip.__version__` |
| `numpy` | Paquete | 2.4.1 | `pip3 show numpy` | `import numpy; numpy.__version__` |
| `pandas` | Paquete | 2.3.3 | `pip3 show pandas` | `import pandas; pandas.__version__` |
| `geopandas` | Paquete | 1.1.2 | `pip3 show geopandas` | `import geopandas; geopandas.__version__` |
| `shapely` | Paquete | 2.1.2 | `pip3 show shapely` | `import shapely; shapely.__version__` |
| `pyproj` | Paquete | 3.7.2 | `pip3 show pyproj` | `import pyproj; pyproj.__version__` |
| `fiona` | Paquete | 1.10.1 | `pip3 show fiona` | `import fiona; fiona.__version__` |
| `rasterio` | Paquete | 1.5.0 | `pip3 show rasterio` | `import rasterio; rasterio.__version__` |
