<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.550">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Programación SIG: Python, R y Julia - Appendix A — Referencia Técnica y Compendio de Comandos</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./92-errata.html" rel="next">
<link href="./71-presentacion_benchmark.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./91-referencia_tecnica.html">Appendices</a></li><li class="breadcrumb-item"><a href="./91-referencia_tecnica.html"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Referencia Técnica y Compendio de Comandos</span></a></li></ol></nav>
        <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Programación SIG: Python, R y Julia</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Bienvenida</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./00-prefacio.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Prefacio</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">Instalación y Entornos</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-introduccion-entornos.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introducción a Entornos de Desarrollo SIG</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-guia_instalacion_A_docker.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Guía de Instalación. Opción A: Contenedor Docker (Python, R, Julia)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-guia_instalacion_B_qgis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Guía de Instalación. Opción B: QGIS y PyQGIS</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-guia_instalacion_C_ArcGIS.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Guía de Instalación. Opción C: ArcGIS Pro y ArcPy</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
 <span class="menu-text">Fundamentos</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-introduccion_python_r_julia.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Fundamentos: Python, R y Julia</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-estructuras_datos_geo.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Estructuras de Datos Geoespaciales</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
 <span class="menu-text">Prácticas</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./41-benchmark_raster.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Benchmark de Procesamiento Geoespacial</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
 <span class="menu-text">Presentaciones</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./71-presentacion_benchmark.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Benchmark geoespacial: cómo leer los resultados</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./91-referencia_tecnica.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Referencia Técnica y Compendio de Comandos</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./92-errata.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Errata</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./93-referencias.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Referencias Bibliográficas</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Tabla de Contenidos</h2>
   
  <ul>
  <li><a href="#introducción-a-la-infraestructura-de-datos" id="toc-introducción-a-la-infraestructura-de-datos" class="nav-link active" data-scroll-target="#introducción-a-la-infraestructura-de-datos"><span class="header-section-number">A.1</span> Introducción a la Infraestructura de Datos</a></li>
  <li><a href="#contenedores-instalados" id="toc-contenedores-instalados" class="nav-link" data-scroll-target="#contenedores-instalados"><span class="header-section-number">A.2</span> Contenedores Instalados</a>
  <ul class="collapse">
  <li><a href="#sec-resumen-infra" id="toc-sec-resumen-infra" class="nav-link" data-scroll-target="#sec-resumen-infra">Resumen de Infraestructura Docker</a></li>
  <li><a href="#batería-de-pruebas-de-integridad-del-docker-health-checks" id="toc-batería-de-pruebas-de-integridad-del-docker-health-checks" class="nav-link" data-scroll-target="#batería-de-pruebas-de-integridad-del-docker-health-checks">🧪 Batería de Pruebas de Integridad del Docker (Health Checks)</a></li>
  <li><a href="#sec-puertos" id="toc-sec-puertos" class="nav-link" data-scroll-target="#sec-puertos">Configuración de Puertos y Conectividad</a></li>
  <li><a href="#sec-credenciales" id="toc-sec-credenciales" class="nav-link" data-scroll-target="#sec-credenciales">🔑 Credenciales de la Base de Datos</a></li>
  <li><a href="#sec-arquitectura-puertos" id="toc-sec-arquitectura-puertos" class="nav-link" data-scroll-target="#sec-arquitectura-puertos">Lógica de Arquitectura (Dockerfile y Compose)</a></li>
  <li><a href="#sec-guia-acceso" id="toc-sec-guia-acceso" class="nav-link" data-scroll-target="#sec-guia-acceso">Guía de Acceso: El concepto de “Lados”</a></li>
  </ul></li>
  <li><a href="#quarto-ref" id="toc-quarto-ref" class="nav-link" data-scroll-target="#quarto-ref"><span class="header-section-number">A.3</span> Quarto: Orquestación y Configuración</a>
  <ul class="collapse">
  <li><a href="#opciones-del-encabezado-yml" id="toc-opciones-del-encabezado-yml" class="nav-link" data-scroll-target="#opciones-del-encabezado-yml">Opciones del encabezado yml</a></li>
  <li><a href="#resumen-de-comandos-quarto" id="toc-resumen-de-comandos-quarto" class="nav-link" data-scroll-target="#resumen-de-comandos-quarto">Resumen de comandos Quarto</a></li>
  <li><a href="#sec-opciones-chunks" id="toc-sec-opciones-chunks" class="nav-link" data-scroll-target="#sec-opciones-chunks">Control de Ejecución en Quarto: Opciones de Chunks</a></li>
  </ul></li>
  <li><a href="#docker-ref" id="toc-docker-ref" class="nav-link" data-scroll-target="#docker-ref"><span class="header-section-number">A.4</span> Docker: Gestión de Contenedores e Imágenes</a>
  <ul class="collapse">
  <li><a href="#procedimiento-incial" id="toc-procedimiento-incial" class="nav-link" data-scroll-target="#procedimiento-incial">Procedimiento Incial</a></li>
  <li><a href="#comandos-docker" id="toc-comandos-docker" class="nav-link" data-scroll-target="#comandos-docker">Comandos Docker</a></li>
  <li><a href="#compilación-avanzada" id="toc-compilación-avanzada" class="nav-link" data-scroll-target="#compilación-avanzada">Compilación Avanzada</a></li>
  <li><a href="#cambio-de-ruta-de-almacenamiento-windows" id="toc-cambio-de-ruta-de-almacenamiento-windows" class="nav-link" data-scroll-target="#cambio-de-ruta-de-almacenamiento-windows">Cambio de Ruta de Almacenamiento (Windows)</a></li>
  <li><a href="#sec-optimizacion-memoria" id="toc-sec-optimizacion-memoria" class="nav-link" data-scroll-target="#sec-optimizacion-memoria">Optimización de Memoria y Swap</a></li>
  <li><a href="#higiene-y-limpieza-de-choque" id="toc-higiene-y-limpieza-de-choque" class="nav-link" data-scroll-target="#higiene-y-limpieza-de-choque">Higiene y Limpieza de Choque</a></li>
  </ul></li>
  <li><a href="#git-ref" id="toc-git-ref" class="nav-link" data-scroll-target="#git-ref"><span class="header-section-number">A.5</span> Git y GitHub: Sincronización Local-Remota</a>
  <ul class="collapse">
  <li><a href="#subír-el-contenido-existende-de-una-carpeta-local-a-un-repositorio-vacío-en-github" id="toc-subír-el-contenido-existende-de-una-carpeta-local-a-un-repositorio-vacío-en-github" class="nav-link" data-scroll-target="#subír-el-contenido-existende-de-una-carpeta-local-a-un-repositorio-vacío-en-github">Subír el contenido existende de una carpeta local a un repositorio vacío en GitHub</a></li>
  <li><a href="#sec-ssh-github" id="toc-sec-ssh-github" class="nav-link" data-scroll-target="#sec-ssh-github">Autenticación Segura: Configuración de Llaves SSH en GitHub</a></li>
  </ul></li>
  <li><a href="#túnel-ssh-activo-y-configurado" id="toc-túnel-ssh-activo-y-configurado" class="nav-link" data-scroll-target="#túnel-ssh-activo-y-configurado"><span class="header-section-number">A.6</span> ¡Túnel SSH Activo y Configurado!</a></li>
  <li><a href="#sec-vinculacion-clase" id="toc-sec-vinculacion-clase" class="nav-link" data-scroll-target="#sec-vinculacion-clase">Vinculación del Repositorio de Contenidos de la Clase</a></li>
  <li><a href="#opción-b-sincronizar-mediante-https" id="toc-opción-b-sincronizar-mediante-https" class="nav-link" data-scroll-target="#opción-b-sincronizar-mediante-https">Opción B: Sincronizar mediante HTTPS</a></li>
  <li><a href="#notas-de-flujo-de-trabajo" id="toc-notas-de-flujo-de-trabajo" class="nav-link" data-scroll-target="#notas-de-flujo-de-trabajo">Notas de Flujo de Trabajo</a></li>
  <li><a href="#vscode-ref" id="toc-vscode-ref" class="nav-link" data-scroll-target="#vscode-ref"><span class="header-section-number">A.7</span> Visual Studio Code: Extensiones e Interfaz</a>
  <ul class="collapse">
  <li><a href="#sec-command-palette" id="toc-sec-command-palette" class="nav-link" data-scroll-target="#sec-command-palette">Atajos de Poder: La Paleta de Comandos</a></li>
  <li><a href="#sec-extensiones-vscode" id="toc-sec-extensiones-vscode" class="nav-link" data-scroll-target="#sec-extensiones-vscode">Configuración de Extensiones en VS Code</a></li>
  <li><a href="#verificación-de-conectividad" id="toc-verificación-de-conectividad" class="nav-link" data-scroll-target="#verificación-de-conectividad">Verificación de Conectividad</a></li>
  </ul></li>
  <li><a href="#shortcuts-ref" id="toc-shortcuts-ref" class="nav-link" data-scroll-target="#shortcuts-ref"><span class="header-section-number">A.8</span> Comandos Rápidos y Shortcuts</a>
  <ul class="collapse">
  <li><a href="#jupyter-notebook-dentro-de-vscode" id="toc-jupyter-notebook-dentro-de-vscode" class="nav-link" data-scroll-target="#jupyter-notebook-dentro-de-vscode">Jupyter Notebook (Dentro de VSCode)</a></li>
  <li><a href="#comandos-de-windows-powershellcmd" id="toc-comandos-de-windows-powershellcmd" class="nav-link" data-scroll-target="#comandos-de-windows-powershellcmd">Comandos de Windows (PowerShell/CMD)</a></li>
  </ul></li>
  <li><a href="#adicionales-sobre-python" id="toc-adicionales-sobre-python" class="nav-link" data-scroll-target="#adicionales-sobre-python"><span class="header-section-number">A.9</span> Adicionales Sobre Python</a>
  <ul class="collapse">
  <li><a href="#versiones-instaladas-del-software" id="toc-versiones-instaladas-del-software" class="nav-link" data-scroll-target="#versiones-instaladas-del-software">Versiones Instaladas del Software</a></li>
  </ul></li>
  <li><a href="#adicionales-sobre-r" id="toc-adicionales-sobre-r" class="nav-link" data-scroll-target="#adicionales-sobre-r"><span class="header-section-number">A.10</span> Adicionales Sobre R</a>
  <ul class="collapse">
  <li><a href="#versiones-instaladas-del-software-1" id="toc-versiones-instaladas-del-software-1" class="nav-link" data-scroll-target="#versiones-instaladas-del-software-1">Versiones Instaladas del Software</a></li>
  <li><a href="#sec-httpgd-config" id="toc-sec-httpgd-config" class="nav-link" data-scroll-target="#sec-httpgd-config">Visualización Interactiva con <code>httpgd</code></a></li>
  <li><a href="#sec-repl-concept" id="toc-sec-repl-concept" class="nav-link" data-scroll-target="#sec-repl-concept">El Entorno Interactivo (REPL) y Motores Gráficos</a></li>
  <li><a href="#sec-interoperabilidad" id="toc-sec-interoperabilidad" class="nav-link" data-scroll-target="#sec-interoperabilidad">Paquetes para Comunicación con Julia y Python</a></li>
  </ul></li>
  <li><a href="#adicionales-sobre-julia" id="toc-adicionales-sobre-julia" class="nav-link" data-scroll-target="#adicionales-sobre-julia"><span class="header-section-number">A.11</span> Adicionales Sobre Julia</a>
  <ul class="collapse">
  <li><a href="#versiones-instaladas-del-software-2" id="toc-versiones-instaladas-del-software-2" class="nav-link" data-scroll-target="#versiones-instaladas-del-software-2">Versiones Instaladas del Software</a></li>
  </ul></li>
  <li><a href="#sec-comandos-so" id="toc-sec-comandos-so" class="nav-link" data-scroll-target="#sec-comandos-so"><span class="header-section-number">A.12</span> Comandos de Terminal (Sistema Operativo)</a>
  <ul class="collapse">
  <li><a href="#verificación-de-librerías-geoespaciales" id="toc-verificación-de-librerías-geoespaciales" class="nav-link" data-scroll-target="#verificación-de-librerías-geoespaciales">Verificación de Librerías Geoespaciales</a></li>
  </ul></li>
  <li><a href="#sec-openssl-surgery" id="toc-sec-openssl-surgery" class="nav-link" data-scroll-target="#sec-openssl-surgery"><span class="header-section-number">A.13</span> La Cirugía de Librerías: El “Cambiazo” de OpenSSL</a>
  <ul class="collapse">
  <li><a href="#el-conflicto-3.0.x-o-3.3.x" id="toc-el-conflicto-3.0.x-o-3.3.x" class="nav-link" data-scroll-target="#el-conflicto-3.0.x-o-3.3.x">1. El Conflicto: ¿3.0.x o 3.3.x?</a></li>
  <li><a href="#la-solución-qué-hace-exactamente-ln--sf" id="toc-la-solución-qué-hace-exactamente-ln--sf" class="nav-link" data-scroll-target="#la-solución-qué-hace-exactamente-ln--sf">2. La Solución: ¿Qué hace exactamente <code>ln -sf</code>?</a></li>
  <li><a href="#por-qué-funciona-si-las-versiones-son-distintas" id="toc-por-qué-funciona-si-las-versiones-son-distintas" class="nav-link" data-scroll-target="#por-qué-funciona-si-las-versiones-son-distintas">3. ¿Por qué funciona si las versiones son distintas?</a></li>
  </ul></li>
  <li><a href="#herramientas-de-admon-de-windows" id="toc-herramientas-de-admon-de-windows" class="nav-link" data-scroll-target="#herramientas-de-admon-de-windows"><span class="header-section-number">A.14</span> Herramientas de admon de Windows</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./91-referencia_tecnica.html">Appendices</a></li><li class="breadcrumb-item"><a href="./91-referencia_tecnica.html"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Referencia Técnica y Compendio de Comandos</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="anexo-referencia" class="quarto-section-identifier">Appendix A — Referencia Técnica y Compendio de Comandos</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="introducción-a-la-infraestructura-de-datos" class="level2" data-number="A.1">
<h2 data-number="A.1" class="anchored" data-anchor-id="introducción-a-la-infraestructura-de-datos"><span class="header-section-number">A.1</span> Introducción a la Infraestructura de Datos</h2>
<p>Este anexo constituye la guía técnico para la gestión del entorno de desarrollo. A diferencia de los capítulos teóricos, aquí nos centramos en la operatividad: cómo configurar el motor de Docker, cómo asegurar que la memoria virtual (Swap) no colapse en procesos masivos, cómo sincronizar el conocimiento mediante Git, y otros temas técnicos (ej. comandos) importantes.</p>
<hr>
</section>
<section id="contenedores-instalados" class="level2" data-number="A.2">
<h2 data-number="A.2" class="anchored" data-anchor-id="contenedores-instalados"><span class="header-section-number">A.2</span> Contenedores Instalados</h2>
<section id="sec-resumen-infra" class="level3">
<h3 class="anchored" data-anchor-id="sec-resumen-infra">Resumen de Infraestructura Docker</h3>
<p>Antes de entrar en los detalles técnicos, es vital entender el rol de los dos archivos maestros que sostienen su laboratorio geográfico.</p>
<table class="table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Archivo</th>
<th style="text-align: left;">Rol Crítico</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong><code>Dockerfile</code></strong></td>
<td style="text-align: left;"><strong>El “Qué” (La Receta):</strong> Crea el entorno políglota desde cero, instala las librerías de NASA/Copernicus y aplica la <strong>“cirugía” de OpenSSL</strong> para que Julia sea estable en Ubuntu Noble.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong><code>docker-compose.yml</code></strong></td>
<td style="text-align: left;"><strong>El “Cómo” (La Orquesta):</strong> Despliega los servicios, mapea los puertos externos (<strong>8889</strong>, <strong>8788</strong>, <strong>5434</strong>) y asegura que sus mapas y bases de datos no se borren gracias al volumen persistente (<code>postgis_data_unal</code>).</td>
</tr>
</tbody>
</table>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Persistencia de Datos
</div>
</div>
<div class="callout-body-container callout-body">
<p>Gracias al <code>docker-compose</code>, si su contenedor se apaga o se reinicia, los datos de su base de datos PostGIS <strong>no se pierden</strong>. El volumen nombrado actúa como un disco duro externo que sobrevive a cualquier caída del sistema.</p>
</div>
</div>
</section>
<section id="batería-de-pruebas-de-integridad-del-docker-health-checks" class="level3">
<h3 class="anchored" data-anchor-id="batería-de-pruebas-de-integridad-del-docker-health-checks">🧪 Batería de Pruebas de Integridad del Docker (Health Checks)</h3>
<table class="table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">ID</th>
<th style="text-align: left;">Comando de Verificación (Docker)</th>
<th style="text-align: left;">Descripción</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">01</td>
<td style="text-align: left;"><code>docker exec contenedor_sig_unal gdalinfo --version</code></td>
<td style="text-align: left;">Verifica que el núcleo de GDAL está activo.</td>
</tr>
<tr class="even">
<td style="text-align: left;">02</td>
<td style="text-align: left;"><code>docker exec contenedor_sig_unal R -e "library(sf); st_point(c(0,0))"</code></td>
<td style="text-align: left;">Prueba la librería <code>sf</code> y el motor de geometría en R.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">03</td>
<td style="text-align: left;"><code>docker exec contenedor_sig_unal python3 -c "import geopandas; print(geopandas.__version__)"</code></td>
<td style="text-align: left;">Verifica el stack espacial de Python.</td>
</tr>
<tr class="even">
<td style="text-align: left;">04</td>
<td style="text-align: left;"><code>docker exec contenedor_sig_unal R -e "j_eval('sum([1, 2, 3])')"</code></td>
<td style="text-align: left;"><strong>Test Crítico:</strong> Verifica la función personalizada y el puente R -&gt; Julia.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">05</td>
<td style="text-align: left;"><code>docker exec contenedor_sig_unal R -e "j_plot('plot(rand(10))')"</code></td>
<td style="text-align: left;">Prueba la generación de gráficos Julia capturados por R.</td>
</tr>
<tr class="even">
<td style="text-align: left;">06</td>
<td style="text-align: left;"><code>docker exec contenedor_sig_unal julia -e 'using ArchGDAL; println(ArchGDAL.GDAL.gdalversioninfo("RELEASE_NAME"))'</code></td>
<td style="text-align: left;"><strong>Cirugía Exitosa:</strong> Confirma que Julia accede a GDAL del sistema (v3.12.1).</td>
</tr>
<tr class="odd">
<td style="text-align: left;">07</td>
<td style="text-align: left;"><code>docker exec contenedor_sig_unal R -e "library(RPostgres); dbConnect(Postgres(), host='db-postgis', dbname='sig_db_unal', user='profe_unal', password='geomatica2025')"</code></td>
<td style="text-align: left;">Prueba la conexión R -&gt; PostGIS (Interna).</td>
</tr>
<tr class="even">
<td style="text-align: left;">08</td>
<td style="text-align: left;"><code>docker exec contenedor_sig_unal python3 -c "import psycopg2; conn = psycopg2.connect(host='db-postgis', dbname='sig_db_unal', user='profe_unal', password='geomatica2025'); print('Python PostGIS conectado ✅'); conn.close()"</code></td>
<td style="text-align: left;">Prueba la conexión Python -&gt; PostGIS (Interna).</td>
</tr>
<tr class="odd">
<td style="text-align: left;">09</td>
<td style="text-align: left;"><code>docker exec contenedor_sig_unal R -e "cat(whitebox::wbt_version())"</code></td>
<td style="text-align: left;">Verifica que los binarios de WhiteboxTools están instalados y accesibles.</td>
</tr>
<tr class="even">
<td style="text-align: left;">10</td>
<td style="text-align: left;"><code>docker exec contenedor_sig_unal R -e "library(httpgd); print('Visor OK')"</code></td>
<td style="text-align: left;">Verifica que el motor gráfico para VS Code está listo en el puerto <code>8787</code>.</td>
</tr>
</tbody>
</table>
</section>
<section id="sec-puertos" class="level3">
<h3 class="anchored" data-anchor-id="sec-puertos">Configuración de Puertos y Conectividad</h3>
<p>Para que su computadora (Host) pueda comunicarse con los servicios dentro del contenedor, hemos diseñado un sistema de “puentes” o mapeo de puertos. Esto evita conflictos si ya tiene instalados otros servidores de bases de datos o Jupyter en su PC.</p>
<table class="table">
<colgroup>
<col style="width: 18%">
<col style="width: 22%">
<col style="width: 22%">
<col style="width: 18%">
<col style="width: 18%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Servicio</th>
<th style="text-align: center;">Puerto en su PC (Host)</th>
<th style="text-align: center;">Puerto en Contenedor</th>
<th style="text-align: left;">Propósito</th>
<th style="text-align: left;">Acceso / Conexión</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Jupyter Lab</strong></td>
<td style="text-align: center;"><code>8889</code></td>
<td style="text-align: center;"><code>8888</code></td>
<td style="text-align: left;">Programación y Notebooks</td>
<td style="text-align: left;"><code>http://localhost:8889</code></td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Visor R (httpgd)</strong></td>
<td style="text-align: center;"><code>8788</code></td>
<td style="text-align: center;"><code>8787</code></td>
<td style="text-align: left;">Gráficos de R y VS Code</td>
<td style="text-align: left;"><code>http://localhost:8788</code></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>PostGIS (DB)</strong></td>
<td style="text-align: center;"><code>5434</code></td>
<td style="text-align: center;"><code>5432</code></td>
<td style="text-align: left;">Base de Datos Espacial</td>
<td style="text-align: left;"><code>localhost:5434</code></td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="sec-credenciales" class="level3">
<h3 class="anchored" data-anchor-id="sec-credenciales">🔑 Credenciales de la Base de Datos</h3>
<p>Utilice estos datos para configurar sus conexiones en QGIS, DBeaver o mediante código (R/Python/Julia):</p>
<ul>
<li><strong>Base de Datos:</strong> <code>sig_db_unal</code></li>
<li><strong>Usuario:</strong> <code>profe_unal</code></li>
<li><strong>Contraseña:</strong> <code>geomatica2025</code></li>
<li><strong>Host Interno:</strong> <code>db-postgis</code> (Use este nombre únicamente para conexiones <strong>dentro</strong> de sus scripts).</li>
</ul>
<hr>
</section>
<section id="sec-arquitectura-puertos" class="level3">
<h3 class="anchored" data-anchor-id="sec-arquitectura-puertos">Lógica de Arquitectura (Dockerfile y Compose)</h3>
<p>La configuración del entorno se ha “blindado” técnicamente para garantizar la estabilidad:</p>
<ol type="1">
<li><strong>En el Dockerfile</strong>: Se usan las instrucciones <code>EXPOSE 8888</code> y <code>EXPOSE 8787</code>. Esto le avisa a Docker que el contenedor tiene dos “puertas” abiertas internamente. Al fijar <code>httpgd.port = 8787</code>, nos aseguramos de que el visor de gráficos de R no pelee con Jupyter por el mismo canal.</li>
<li><strong>En el Docker-Compose</strong>:
<ul>
<li><strong><code>8889:8888</code></strong>: Permite que este curso conviva con otras instalaciones de Jupyter (que suelen usar el 8888).</li>
<li><strong><code>8788:8787</code></strong>: Habilita la conexión independiente de VS Code al visor de gráficos de R.</li>
<li><strong><code>5434:5432</code></strong>: Evita el choque con bases de datos locales (Postgres suele usar el 5432 o 5433).</li>
</ul></li>
</ol>
<hr>
</section>
<section id="sec-guia-acceso" class="level3">
<h3 class="anchored" data-anchor-id="sec-guia-acceso">Guía de Acceso: El concepto de “Lados”</h3>
<p>Es fundamental entender desde dónde está intentando conectar:</p>
<blockquote class="blockquote">
<h4 id="desde-afuera-su-pc-host" class="anchored">🌐 Desde afuera (Su PC / Host)</h4>
<p>Es lo que usted configura en su navegador o en QGIS. Usted ve los puertos mapeados: * <strong>Jupyter/Notebooks</strong>: <code>http://localhost:8889</code> (usando el token <code>geomatica2025</code>). * <strong>Base de Datos (QGIS/DBeaver)</strong>: Host: <code>localhost</code>, Puerto: <code>5434</code>.</p>
</blockquote>
<blockquote class="blockquote">
<h4 id="desde-adentro-el-contenedor" class="anchored">🐳 Desde adentro (El Contenedor)</h4>
<p>Sus scripts de Python, R y Julia no saben que existe un mapeo externo. Dentro de su “casa” Docker, nada ha cambiado: * <strong>PostGIS</strong>: El código debe buscar el puerto estándar <code>5432</code> y el host <code>db-postgis</code>. * <strong>httpgd</strong>: El servidor de gráficos sigue escuchando en el puerto interno <code>8787</code>.</p>
</blockquote>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip de Conexión
</div>
</div>
<div class="callout-body-container callout-body">
<p>Si intenta conectar QGIS usando el puerto <code>5432</code> y falla, recuerde que el “puente” hacia el contenedor se construyó específicamente sobre el puerto <strong><code>5434</code></strong>.</p>
</div>
</div>
</section>
</section>
<section id="quarto-ref" class="level2" data-number="A.3">
<h2 data-number="A.3" class="anchored" data-anchor-id="quarto-ref"><span class="header-section-number">A.3</span> Quarto: Orquestación y Configuración</h2>
<p>Quarto se basa en un archivo de configuración centralizado donde se definen los parámetros de renderizado, bibliografía y estilos.</p>
<section id="opciones-del-encabezado-yml" class="level3">
<h3 class="anchored" data-anchor-id="opciones-del-encabezado-yml">Opciones del encabezado yml</h3>
<p><strong>Ejemplo 1</strong>: Solo HTML</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Título de la Práctica"</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Nombre del Estudiante"</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> last-modified</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co">    toc: true</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="co">    toc-depth: 3</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="co">    toc-location: left</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="co">    number-sections: true</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="co">    theme: lux</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><strong>Ejemplo 2</strong>: HTML y Python</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Informe Técnico: Análisis Geoespacial"</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "ID Correo UNAL"</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> today</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="co">    toc: true</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="co">    number-sections: true</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="co">    theme: cosmo</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a><span class="co">  pdf:</span></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a><span class="co">    toc: true</span></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a><span class="co">    toc-title: "Contenido"</span></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a><span class="co">    number-sections: true</span></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a><span class="co">    documentclass: scrreprt</span></span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a><span class="co">    geometry:</span></span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a><span class="co">      - top=25mm</span></span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a><span class="co">      - left=25mm</span></span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a><span class="co">      - right=25mm</span></span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a><span class="co">      - bottom=25mm</span></span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="resumen-de-comandos-quarto" class="level3">
<h3 class="anchored" data-anchor-id="resumen-de-comandos-quarto">Resumen de comandos Quarto</h3>
<p><code>quarto render guia_instalacion.qmd --to all</code></p>
<p><code>quarto render guia_instalacion.qmd --to html</code></p>
<p><code>quarto render guia_instalacion.qmd --to pdf</code></p>
</section>
<section id="sec-opciones-chunks" class="level3">
<h3 class="anchored" data-anchor-id="sec-opciones-chunks">Control de Ejecución en Quarto: Opciones de Chunks</h3>
<p>Para que sus informes técnicos sean profesionales, no basta con que el código funcione; es necesario controlar qué se muestra y qué se oculta al lector final. En Quarto, esto se logra mediante el uso de “opciones de chunk” utilizando la sintaxis de la tubería de comentarios (<code>#|</code>).</p>
<table class="table">
<colgroup>
<col style="width: 17%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Opción de Chunk</th>
<th style="text-align: center;">¿Se ejecuta?</th>
<th style="text-align: center;">¿Muestra el Código?</th>
<th style="text-align: center;">¿Muestra Resultados / Plots?</th>
<th style="text-align: left;">Uso Ideal</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong><code>#| echo: false</code></strong></td>
<td style="text-align: center;">✅ SÍ</td>
<td style="text-align: center;">❌ NO</td>
<td style="text-align: center;">✅ SÍ</td>
<td style="text-align: left;"><strong>Para Resultados Finales.</strong> Muestra el mapa/tabla sin la “receta”.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong><code>#| include: false</code></strong></td>
<td style="text-align: center;">✅ SÍ</td>
<td style="text-align: center;">❌ NO</td>
<td style="text-align: center;">❌ NO</td>
<td style="text-align: left;"><strong>Para el Setup.</strong> Corre todo en secreto, sin mensajes ni advertencias.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong><code>#| code-fold: true</code></strong></td>
<td style="text-align: center;">✅ SÍ</td>
<td style="text-align: center;">📂 Plegado</td>
<td style="text-align: center;">✅ SÍ</td>
<td style="text-align: left;"><strong>Para el Proceso.</strong> El código se oculta tras un botón “Code”.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong><code>#| eval: false</code></strong></td>
<td style="text-align: center;">❌ NO</td>
<td style="text-align: center;">✅ SÍ</td>
<td style="text-align: center;">❌ NO</td>
<td style="text-align: left;"><strong>Para Tutoriales.</strong> Solo muestra el texto del código sin procesarlo.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong><code>#| output: false</code></strong></td>
<td style="text-align: center;">✅ SÍ</td>
<td style="text-align: center;">✅ SÍ</td>
<td style="text-align: center;">❌ NO</td>
<td style="text-align: left;"><strong>Para Debugging.</strong> Ves su código pero no los resultados pesados.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong><code>#| warning: false</code></strong></td>
<td style="text-align: center;">✅ SÍ</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
<td style="text-align: left;">Oculta esos textos naranjas de advertencia de las librerías.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong><code>#| message: false</code></strong></td>
<td style="text-align: center;">✅ SÍ</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
<td style="text-align: left;">Oculta mensajes de carga (ej: “Loading terra package…”).</td>
</tr>
</tbody>
</table>
<hr>
<section id="recomendaciones-de-uso-según-el-contexto" class="level4">
<h4 class="anchored" data-anchor-id="recomendaciones-de-uso-según-el-contexto">Recomendaciones de Uso según el Contexto</h4>
<p>Dependiendo de la parte del script en la que se encuentre, existen configuraciones que garantizan un documento más limpio y fluido:</p>
<table class="table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Tipo de Chunk</th>
<th style="text-align: left;">Opción recomendada</th>
<th style="text-align: left;">¿Por qué?</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Setup / Librerías</strong></td>
<td style="text-align: left;"><code>#| include: false</code></td>
<td style="text-align: left;">Ejecuta todo pero oculta el código y los mensajes de carga de R/Julia/Python.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Limpieza de RAM</strong></td>
<td style="text-align: left;"><code>#| include: false</code></td>
<td style="text-align: left;">Borra objetos y vacía el cache en silencio. El lector no necesita ver la “limpieza”.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Procesamiento</strong></td>
<td style="text-align: left;"><code>#| code-fold: true</code></td>
<td style="text-align: left;">Muestra el mapa pero esconde el código tras un clic. Ideal para transparencia académica.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Resultados Finales</strong></td>
<td style="text-align: left;"><code>#| echo: false</code></td>
<td style="text-align: left;">Muestra solo la tabla comparativa y conclusiones. Es el “veredicto” limpio y profesional.</td>
</tr>
</tbody>
</table>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Sintaxis Correcta
</div>
</div>
<div class="callout-body-container callout-body">
<p>Recuerde que las opciones deben ir al inicio del chunk, justo después de los corchetes del lenguaje:</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning: false</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(terra)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Su código aquí...</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</section>
</section>
</section>
<section id="docker-ref" class="level2" data-number="A.4">
<h2 data-number="A.4" class="anchored" data-anchor-id="docker-ref"><span class="header-section-number">A.4</span> Docker: Gestión de Contenedores e Imágenes</h2>
<section id="procedimiento-incial" class="level3">
<h3 class="anchored" data-anchor-id="procedimiento-incial">Procedimiento Incial</h3>
<p>Antes de trabajar con Docker debes:</p>
<ol type="1">
<li><p>Arrancar Docker Desktop</p></li>
<li><p>Usando la terminal <strong>PowerShell</strong> de Windows ubicarte sobre la carpeta dónde se encuentran los archivos <code>Dockerfile</code> y <code>docker-compose.html</code></p></li>
</ol>
<p>Los siguientes pasos son <strong>compilar</strong> (solo una vez), arrancar las imágenes y detener las imágenes:</p>
<ol start="3" type="1">
<li><strong>Compilación Limpia (Sin Cache) con Log:</strong></li>
</ol>
<div class="sourceCode" id="cb4"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="ex">docker</span> build <span class="at">--no-cache</span> <span class="at">-t</span> mi_sig_env:v1 . <span class="op">&gt;</span> build_details.log <span class="dv">2</span><span class="op">&gt;&amp;</span><span class="dv">1</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<ol start="4" type="1">
<li><strong>Arrancar las imágenes:</strong></li>
</ol>
<div class="sourceCode" id="cb5"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="ex">docker</span> compose up <span class="at">-d</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<ol start="5" type="1">
<li><strong>Detener las imágenes:</strong> (opcional: solo para terminar)</li>
</ol>
<div class="sourceCode" id="cb6"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="ex">docker</span> compose down</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Finalmente trabajar con los contenedores dentro de VSCode:</p>
<ol start="6" type="1">
<li>“Ctrl + Shif + P”: “Dev Containers: Attach to Running Container…” y seleccionar container <code>image_sig_unal</code> (<code>contenedor_sig_unal</code>)</li>
</ol>
</section>
<section id="comandos-docker" class="level3">
<h3 class="anchored" data-anchor-id="comandos-docker">Comandos Docker</h3>
<p>Use la siguiente tabla como referencia para gestionar sus contenedores desde la terminal de su sistema anfitrión (Windows/Mac/Linux).</p>
<table class="table">
<colgroup>
<col style="width: 20%">
<col style="width: 40%">
<col style="width: 40%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Acción</th>
<th style="text-align: left;">Comando</th>
<th style="text-align: left;">Propósito</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Construcción Inicial</strong></td>
<td style="text-align: left;"><code>docker-compose up --build -d</code></td>
<td style="text-align: left;">Compila el Dockerfile y levanta los servicios (Solo una vez).</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Inicio Diario</strong></td>
<td style="text-align: left;"><code>docker-compose up -d</code></td>
<td style="text-align: left;">Inicia los servicios de forma instantánea si ya fueron construidos.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Monitoreo de Procesos</strong></td>
<td style="text-align: left;"><code>docker logs -f entorno_unal_sig</code></td>
<td style="text-align: left;">Sigue los logs en vivo (ideal para ver pre-compilaciones).</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Ver logs recientes</strong></td>
<td style="text-align: left;"><code>docker logs --tail 20 entorno_unal_sig</code></td>
<td style="text-align: left;">Muestra las últimas 20 líneas (ideal para buscar el token).</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Apagado</strong></td>
<td style="text-align: left;"><code>docker-compose down</code></td>
<td style="text-align: left;">Detiene los servicios y libera recursos del sistema.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Prueba de R (sf)</strong></td>
<td style="text-align: left;"><code>docker exec entorno_unal_sig R -e "library(sf); print('R-Spatial detectado')"</code></td>
<td style="text-align: left;">Confirmar que R reconoce los drivers geoespaciales del sistema.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Prueba de Python</strong></td>
<td style="text-align: left;"><code>docker exec entorno_unal_sig python -c "import shapely; import geopandas; print('Python OK')"</code></td>
<td style="text-align: left;">Confirmar que el stack de Python (GeoPandas/Shapely) está instalado.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Prueba de Julia</strong></td>
<td style="text-align: left;"><code>docker exec entorno_unal_sig julia -e "using LibGEOS; println('Julia OK')"</code></td>
<td style="text-align: left;">Confirmar que Julia tiene acceso a los binarios geoespaciales.</td>
</tr>
</tbody>
</table>
</section>
<section id="compilación-avanzada" class="level3">
<h3 class="anchored" data-anchor-id="compilación-avanzada">Compilación Avanzada</h3>
<p>Para trabajar con entornos SIG, a menudo necesitamos reconstruir imágenes sin basura previa.</p>
<ul>
<li><strong>Compilación Limpia (Sin Cache) con Log:</strong> Para asegurar que Docker descargue todas las librerías desde cero y guarde un registro detallado de los errores: <code>docker build --no-cache -t mi_sig_env:v1 . --progress=plain &gt; build_details.log 2&gt;&amp;1</code></li>
<li><strong>Subir Imagen a Repositorio:</strong> <code>docker tag mi_sig_env:v1 usuario_dockerhub/mi_sig_env:v1</code> <code>docker push usuario_dockerhub/mi_sig_env:v1</code></li>
<li><strong>Cargar en VSCode:</strong> Una vez el contenedor esté corriendo, use la extensión <strong>Dev Containers</strong> -&gt; Botón verde inferior izquierdo -&gt; <em>Attach to Running Container</em>.</li>
</ul>
</section>
<section id="cambio-de-ruta-de-almacenamiento-windows" class="level3">
<h3 class="anchored" data-anchor-id="cambio-de-ruta-de-almacenamiento-windows">Cambio de Ruta de Almacenamiento (Windows)</h3>
<p>Si el disco <code>C:</code> se agota debido a las imágenes de Docker, siga estos pasos en <strong>Docker Desktop</strong>: 1. Vaya a <strong>Settings</strong> (engranaje). 2. <strong>Resources</strong> &gt; <strong>Advanced</strong>. 3. En <strong>Disk image location</strong>, cambie la ruta a un disco con mayor capacidad (ej. <code>D:\DockerImages</code>). 4. Presione <strong>Apply &amp; Restart</strong>.</p>
</section>
<section id="sec-optimizacion-memoria" class="level3">
<h3 class="anchored" data-anchor-id="sec-optimizacion-memoria">Optimización de Memoria y Swap</h3>
<p>Cuando procesamos datos masivos (como imágenes Sentinel-2 o rásters globales), la RAM física de 16GB suele ser insuficiente. Para evitar que el sistema aborte los procesos con el error <strong>“Killed”</strong>, debemos configurar un “pulmón” de emergencia en dos niveles.</p>
<section id="el-pulmón-de-windows-memoria-virtual" class="level4">
<h4 class="anchored" data-anchor-id="el-pulmón-de-windows-memoria-virtual">1. El “Pulmón” de Windows: Memoria Virtual</h4>
<p>Obligamos a Windows a usar el disco duro como si fuera RAM de reserva. Si tiene un disco sólido (SSD) secundario con mucho espacio libre (ej. Disco D:), es el lugar ideal para configurarlo.</p>
<ol type="1">
<li>En el buscador de Windows, escriba: <strong>“Ajustar la apariencia y rendimiento de Windows”</strong>.</li>
<li>Vaya a la pestaña <strong>Opciones avanzadas</strong> &gt; sección <strong>Memoria virtual</strong> &gt; clic en <strong>Cambiar</strong>.</li>
<li>Desmarque la opción “Administrar automáticamente el tamaño del archivo de paginación para todas las unidades”.</li>
<li>Seleccione la unidad de disco (C: o D:) y marque <strong>Tamaño personalizado</strong>.</li>
<li>Establezca los siguientes valores (recomendados para este curso):
<ul>
<li><strong>Tamaño inicial</strong>: <code>16384</code> MB (16 GB).</li>
<li><strong>Tamaño máximo</strong>: <code>32768</code> MB (32 GB).</li>
</ul></li>
<li>Haga clic en <strong>Establecer</strong>, luego en <strong>Aceptar</strong> y <strong>reinicie su computadora</strong> para aplicar los cambios.</li>
</ol>
</section>
<section id="el-túnel-de-docker-swap-de-wsl2" class="level4">
<h4 class="anchored" data-anchor-id="el-túnel-de-docker-swap-de-wsl2">2. El “Túnel” de Docker: Swap de WSL2</h4>
<p>Docker Desktop corre sobre WSL2 (<em>Windows Subsystem for Linux</em>), el cual tiene su propio “presupuesto” limitado. Por defecto, este túnel es estrecho (máximo 4GB de Swap). Si no ampliamos esto, el contenedor nunca podrá aprovechar realmente el espacio que le asignamos a Windows.</p>
<p><strong>Cómo ampliar la tubería:</strong> 1. Presione <code>Win + R</code>, escriba <code>%UserProfile%</code> y presione Enter. 2. Busque el archivo <code>.wslconfig</code>. Si no existe, créelo con el Bloc de Notas. 3. Pegue el siguiente contenido:</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode ini code-with-copy"><code class="sourceCode ini"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="kw">[wsl2]</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="dt">memory</span><span class="ot">=</span><span class="st">12GB # RAM máxima que le permitimos usar a Linux/Docker</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="dt">swap</span><span class="ot">=</span><span class="st">16GB   # El nuevo tamaño de swap que verá el comando 'top' en la terminal</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<ol start="4" type="1">
<li><strong>Aplicar cambios</strong>: Guarde el archivo, abra una terminal (PowerShell) y escriba <code>wsl --shutdown</code>. Luego, inicie Docker Desktop nuevamente.</li>
</ol>
<hr>
</section>
</section>
<section id="higiene-y-limpieza-de-choque" class="level3">
<h3 class="anchored" data-anchor-id="higiene-y-limpieza-de-choque">Higiene y Limpieza de Choque</h3>
<p>Para garantizar que un renderizado de Quarto llegue al 100% sin colapsar el contenedor, aplique estas medidas de higiene:</p>
<ul>
<li><strong>Cierre “Vampiros”</strong>: Aplicaciones como Chrome, Edge, Teams y Slack consumen RAM de forma agresiva. Ciérrelas antes de procesos pesados.</li>
<li><strong>Limpieza de disco</strong>: Use el Liberador de espacio en disco (<code>cleanmgr</code>) para vaciar archivos de volcado de memoria.</li>
<li><strong>La “Escoba” en el Código</strong>: Use comandos de limpieza entre procesos de diferentes lenguajes:
<ul>
<li><strong>R</strong>: <code>rm(obj); gc(full = TRUE)</code></li>
<li><strong>Python</strong>: <code>del var; gc.collect()</code></li>
<li><strong>Julia</strong>: <code>GC.gc()</code></li>
</ul></li>
</ul>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Importante para Visualización
</div>
</div>
<div class="callout-body-container callout-body">
<p>En Julia y R, evite generar gráficos interactivos pesados dentro de bucles de procesamiento. La acumulación de objetos visuales en la memoria de VS Code es la causa número uno de colapsos en el contenedor.</p>
</div>
</div>
</section>
</section>
<section id="git-ref" class="level2" data-number="A.5">
<h2 data-number="A.5" class="anchored" data-anchor-id="git-ref"><span class="header-section-number">A.5</span> Git y GitHub: Sincronización Local-Remota</h2>
<section id="subír-el-contenido-existende-de-una-carpeta-local-a-un-repositorio-vacío-en-github" class="level3">
<h3 class="anchored" data-anchor-id="subír-el-contenido-existende-de-una-carpeta-local-a-un-repositorio-vacío-en-github">Subír el contenido existende de una carpeta local a un repositorio vacío en GitHub</h3>
<p>Si ya tiene sus archivos en Windows y quiere subirlos a un repositorio recién creado en GitHub:</p>
<ol type="1">
<li><strong>Instalar Git</strong></li>
</ol>
<ul>
<li><strong>Descarga</strong>: Acceda a <a href="https://git-scm.com/download/win">git-scm.com/download/win</a>.</li>
<li><strong>Instalación</strong>: Ejecute el instalador manteniendo las opciones por defecto; asegúrese de que la opción <strong>“Git from the command line and also from 3rd-party software”</strong> esté activa.</li>
<li><strong>Verificación</strong>: Ejecute <code>git --version</code> en una terminal para confirmar la instalación.</li>
</ul>
<ol start="2" type="1">
<li><p><strong>Crear una cuenta en GitHub</strong></p></li>
<li><p><strong>Abrir Terminal en la carpeta local:</strong></p></li>
<li><p><strong>Incicializar Git</strong> en la carpeta local:</p></li>
</ol>
<div class="sourceCode" id="cb8"><pre class="sourceCode powershell code-with-copy"><code class="sourceCode powershell"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>git init</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<ol start="5" type="1">
<li>Ver el <strong>estado actual</strong> del repositorio Git:</li>
</ol>
<div class="sourceCode" id="cb9"><pre class="sourceCode powershell code-with-copy"><code class="sourceCode powershell"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>git status</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<ol start="6" type="1">
<li><strong>Archivo <code>.gitignore</code></strong>: Crear un archivo de texto <code>.gitignore</code> para indicarle a Git que archivos y carperas nunca deben ser registrados con Git. A continuación un archivo de ejemplo:</li>
</ol>
<pre class="text"><code>.quarto/
_freeze/
.ipynb_checkpoints/
__pycache__/
*.pdf
*.html
notebooks/
scripts/
data/</code></pre>
<ol start="7" type="1">
<li><strong>Registrar (add)</strong> el archivo <code>.gitignore</code> con Git:</li>
</ol>
<div class="sourceCode" id="cb11"><pre class="sourceCode powershell code-with-copy"><code class="sourceCode powershell"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>git add <span class="op">.</span><span class="fu">gitignore</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<ol start="8" type="1">
<li>Revise nuevamente el <strong>estátus</strong> y verifique cambios:</li>
</ol>
<div class="sourceCode" id="cb12"><pre class="sourceCode powershell code-with-copy"><code class="sourceCode powershell"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>git status</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<ol start="9" type="1">
<li><strong>Salvar (commit)</strong> el archivo en Git (local). Note que en el comando, el texto “<em>Archivo .gitignore</em>” es un comentario que describe lo que está salvando:</li>
</ol>
<div class="sourceCode" id="cb13"><pre class="sourceCode powershell code-with-copy"><code class="sourceCode powershell"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>git commit <span class="op">-</span>m <span class="st">"Archivo .gitignore"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<ol start="10" type="1">
<li>Cambiar al nombre de <strong>rama (branch)</strong> a <strong>principal (main)</strong>. Pueden haber diferentes ramas con diferentes versiones del mismo archivo. Para cambiar a <strong>main</strong>:</li>
</ol>
<div class="sourceCode" id="cb14"><pre class="sourceCode powershell code-with-copy"><code class="sourceCode powershell"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>git branch <span class="op">-</span>M main</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<ol start="11" type="1">
<li><strong>Conectar</strong> el repositorio local (Git) con nuestro repositorio en GitHub.</li>
</ol>
<p>Para conectar Git con GitHub, puede hacerlo con SSH (debe realizar el proceso de instalación de llaves <a href="#sec-ssh-github" class="quarto-xref"><span>Section A.5.2</span></a>) o con HTTPS (debe generar un PAT desde <code>github.com</code> que usará como clave de autenticación). En este caso usaremos HTTPS.</p>
<p>Cree un nuevo repositorio en GitHub y copie la url HTTP del repositorio. Es algo como: <code>https://github.com/usuario/repositorio.git</code></p>
<div class="sourceCode" id="cb15"><pre class="sourceCode powershell code-with-copy"><code class="sourceCode powershell"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>git remote add origin https<span class="op">://</span>github<span class="op">.</span><span class="fu">com</span><span class="op">/</span>usuario<span class="op">/</span>repositorio<span class="op">.</span><span class="fu">git</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<ol start="12" type="1">
<li>Procedimiento para <strong>generar el PAT</strong> en GitHub.com {#github-pat}</li>
</ol>
<ul>
<li>En lugar de escribir tu contraseña cuando el terminal te la pida, debes pegar un token generado en tu cuenta.</li>
<li>Ve a tu cuenta de GitHub.com: <code>Settings</code> &gt; <code>Developer settings</code> &gt; <code>Personal access tokens</code> &gt; <code>Tokens (classic)</code>.</li>
<li>Genera un nuevo token <strong>con el permiso repo activado.</strong></li>
<li>Copia el token (no lo volverás a ver).</li>
</ul>
<ol start="13" type="1">
<li><strong>Subir (push)</strong> la información guardada localmente en Git a nuestro repositorio en GitHub:</li>
</ol>
<div class="sourceCode" id="cb16"><pre class="sourceCode powershell code-with-copy"><code class="sourceCode powershell"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>git push <span class="op">-</span>u origin main   </span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Cuanto solicite el password use el PAT/token generado previamente en github.com</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Puedes ver el estatus <code>git status</code> y realizar un procedimiento similar para registrar (<code>add</code>), salvar (<code>commit</code>) y subir (<code>push</code>) mas archivos.</p>
<ul>
<li>Registrar archivos específicos con Git (local):</li>
</ul>
<div class="sourceCode" id="cb17"><pre class="sourceCode powershell code-with-copy"><code class="sourceCode powershell"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>git add file1 file2 <span class="op">...</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<ul>
<li>Registrar <strong>todos los archivos y carpetas</strong> disponibles y sin registrar, sin embargo todos los archivos y carpetas dentro de <code>.gitignore</code> no serán tenidos en cuenta:</li>
</ul>
<div class="sourceCode" id="cb18"><pre class="sourceCode powershell code-with-copy"><code class="sourceCode powershell"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>git add <span class="op">.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<ul>
<li><p>En <strong>resumen</strong> estos son los comandos que usarás permanentemente para mentener sincronizados tus archivos con Git y tu Git con GitHub.</p></li>
<li><p><code>git add</code> (agregar archivos a Git)</p></li>
<li><p><code>git commit</code> (guardar archivos en Git)</p></li>
<li><p><code>git push</code> (subir archivos a GitHub)</p></li>
<li><p>Los otros comandos vistos solo se ejecutan <strong>una vez</strong> o de acuerdo con <strong>necesitades específicas</strong>:</p></li>
<li><p><code>git init</code> (una vez)</p></li>
<li><p><code>git remote add origin</code> (una vez)</p></li>
<li><p><code>git branch -M main</code> (lo debes usar para cambiar a main en caso de tener múltiples ramas)</p></li>
</ul>
</section>
<section id="sec-ssh-github" class="level3">
<h3 class="anchored" data-anchor-id="sec-ssh-github">Autenticación Segura: Configuración de Llaves SSH en GitHub</h3>
<p>La autenticación mediante SSH permite interactuar con GitHub de forma segura sin necesidad de ingresar credenciales manualmente en cada operación. Siga este procedimiento detallado para configurar su acceso.</p>
<section id="requitiso-previo-creación-de-cuenta-en-github" class="level4">
<h4 class="anchored" data-anchor-id="requitiso-previo-creación-de-cuenta-en-github">Requitiso Previo: Creación de Cuenta en GitHub</h4>
<p>El correo que use para crear esta cuenta <strong>debe ser el mismo correo</strong> usado para crear las llaves SSH para conexión automática.</p>
</section>
<section id="requisito-previo-instalación-de-git" class="level4">
<h4 class="anchored" data-anchor-id="requisito-previo-instalación-de-git">Requisito Previo: Instalación de Git</h4>
<p>Es indispensable que su sistema operativo cuente con el motor de Git antes de iniciar la configuración:</p>
</section>
<section id="preparación-del-entorno-local" class="level4">
<h4 class="anchored" data-anchor-id="preparación-del-entorno-local">Preparación del Entorno Local</h4>
<ul>
<li><strong>Navegación</strong>: Diríjase mediante el Explorador de Archivos a la carpeta raíz de su proyecto (ejemplo: carpeta <code>ID Unal</code>).</li>
<li><strong>Terminal</strong>: Abra una ventana de PowerShell en esa ubicación (clic derecho -&gt; <strong>“Abrir en Terminal”</strong>).</li>
<li><strong>Inicialización</strong>: Prepare el repositorio local mediante el comando:</li>
</ul>
<div class="sourceCode" id="cb19"><pre class="sourceCode powershell code-with-copy"><code class="sourceCode powershell"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>git init</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<hr>
</section>
<section id="gestión-de-llaves-ssh-en-windows" class="level4">
<h4 class="anchored" data-anchor-id="gestión-de-llaves-ssh-en-windows">Gestión de Llaves SSH en Windows</h4>
<p><strong>SSH</strong> (<em>Secure Shell</em>) es un protocolo de red diseñado para el acceso, administración y transferencia de datos entre un equipo local y un servidor remoto mediante un canal cifrado. En nuestro flujo de trabajo, implementamos el algoritmo <strong>Ed25519</strong>, un estándar de vanguardia basado en criptografía de curva elíptica (EdDSA). Este método no solo ofrece un nivel de seguridad superior frente a ataques de fuerza bruta, sino que permite una <strong>autenticación transparente y sin contraseña</strong>, actuando como un “pasaporte digital” que vincula de forma única su estación de trabajo con GitHub.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
¿Por qué Ed25519?
</div>
</div>
<div class="callout-body-container callout-body">
<p>A diferencia de los estándares antiguos (como RSA), <strong>Ed25519</strong> genera llaves más cortas, rápidas y significativamente más seguras, optimizando la latencia en cada comunicación con el repositorio.</p>
</div>
</div>
<ul>
<li><strong>Comprobación de llaves existentes</strong>: Verifique si su usuario ya posee llaves configuradas:</li>
</ul>
<div class="sourceCode" id="cb20"><pre class="sourceCode powershell code-with-copy"><code class="sourceCode powershell"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ls</span> <span class="op">~/.</span><span class="fu">ssh</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre><code>* Si el directorio está vacío o solo contiene `known_hosts`, proceda a generar una nueva.
* Si visualiza los archivos `id_ed25519` e `id_ed25519.pub`, puede saltar al paso de registro en GitHub.</code></pre>
<ul>
<li><strong>Generación de llaves</strong>: Cree un par de llaves seguras utilizando el algoritmo Ed25519:</li>
</ul>
<p>El correo que use en el siguiente paso, <strong>debe</strong> ser el correo con el que creó la cuenta de GitHub: “su_correo@domimio.com”</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode powershell code-with-copy"><code class="sourceCode powershell"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>ssh-keygen <span class="op">-</span>t ed25519 <span class="op">-</span>C <span class="st">"su_correo@domimio.com"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre><code>* **Nota**: Presione `ENTER` en todas las solicitudes para aceptar las rutas por defecto y no asignar una *passphrase*.</code></pre>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Seguridad de la Identidad
</div>
</div>
<div class="callout-body-container callout-body">
<p>La <strong>llave pública</strong> (<code>id_ed25519.pub</code>) es la que se entrega a GitHub, mientras que la <strong>llave privada</strong> (<code>id_ed25519</code>) funciona como su sello personal secreto y nunca debe salir de su equipo.</p>
</div>
</div>
</section>
<section id="registro-de-la-identidad-en-github" class="level4">
<h4 class="anchored" data-anchor-id="registro-de-la-identidad-en-github">Registro de la Identidad en GitHub</h4>
<ul>
<li><strong>Copiar la firma pública</strong>: Obtenga el contenido de su llave para registrarla:</li>
</ul>
<div class="sourceCode" id="cb24"><pre class="sourceCode powershell code-with-copy"><code class="sourceCode powershell"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span> <span class="va">$env</span><span class="op">:</span><span class="va">USERPROFILE</span>\<span class="op">.</span><span class="fu">ssh</span>\id_ed25519<span class="op">.</span><span class="fu">pub</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>    <span class="ch">``</span>`</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>    <span class="op">*</span>Seleccione y copie toda la cadena de texto resultante<span class="op">.*</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a><span class="op">*</span> <span class="op">**</span>Configuración en la plataforma<span class="op">**:</span></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>    <span class="op">*</span> Acceda a su cuenta en <span class="op">[</span>GitHub<span class="op">.</span><span class="fu">com</span><span class="op">](</span>https<span class="op">://</span>github<span class="op">.</span><span class="fu">com</span><span class="op">).</span></span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>    <span class="op">*</span> Entre a <span class="op">**</span>Settings<span class="op">**</span> <span class="op">-&gt;</span> <span class="op">**</span>SSH and GPG keys<span class="op">**.</span></span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>    <span class="op">*</span> Seleccione <span class="op">**</span>New SSH key<span class="op">**.</span></span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>    <span class="op">*</span> Asigne el título <span class="ch">`W</span>indows-UNAL-2025<span class="ch">`,</span> pegue el contenido en el campo <span class="op">**</span>Key<span class="op">**</span> y presione <span class="op">**</span>Add SSH key<span class="op">**.</span></span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a><span class="co">#### Activación del Agente SSH del Sistema</span></span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-14"><a href="#cb24-14" aria-hidden="true" tabindex="-1"></a>Para que Windows gestione su identidad de forma transparente<span class="op">,</span> debe habilitar el servicio correspondiente<span class="op">:</span></span>
<span id="cb24-15"><a href="#cb24-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-16"><a href="#cb24-16" aria-hidden="true" tabindex="-1"></a><span class="op">*</span> <span class="op">**</span>Modo Administrador<span class="op">**:</span> Cierre su terminal actual y abra una nueva sesión de <span class="op">**</span>PowerShell como Administrador<span class="op">**.</span></span>
<span id="cb24-17"><a href="#cb24-17" aria-hidden="true" tabindex="-1"></a><span class="op">*</span> <span class="op">**</span>Habilitar Servicio<span class="op">**:</span> Ejecute los siguientes comandos para automatizar el arranque <span class="fu">del</span> agente<span class="op">:</span></span>
<span id="cb24-18"><a href="#cb24-18" aria-hidden="true" tabindex="-1"></a><span class="ch">```p</span>owershell</span>
<span id="cb24-19"><a href="#cb24-19" aria-hidden="true" tabindex="-1"></a><span class="fu">Set-Service</span> ssh-agent <span class="op">-</span>StartupType Automatic</span>
<span id="cb24-20"><a href="#cb24-20" aria-hidden="true" tabindex="-1"></a><span class="fu">Start-Service</span> ssh-agent</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<ul>
<li><strong>Cargar la llave privada</strong>: Registre su llave en el agente activo:</li>
</ul>
<div class="sourceCode" id="cb25"><pre class="sourceCode powershell code-with-copy"><code class="sourceCode powershell"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>ssh-add <span class="va">$env</span><span class="op">:</span><span class="va">USERPROFILE</span>\<span class="op">.</span><span class="fu">ssh</span>\id_ed25519</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="verificación-de-la-autenticación" class="level4">
<h4 class="anchored" data-anchor-id="verificación-de-la-autenticación">Verificación de la Autenticación</h4>
<ul>
<li><strong>Prueba de conexión</strong>: Compruebe que el túnel de comunicación con los servidores de GitHub funciona correctamente:</li>
</ul>
<div class="sourceCode" id="cb26"><pre class="sourceCode powershell code-with-copy"><code class="sourceCode powershell"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>ssh <span class="op">-</span>T git@github<span class="op">.</span><span class="fu">com</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<ul>
<li><strong>Resultado esperado</strong>: Si la configuración es exitosa, recibirá un mensaje similar a: <code>Hi usuario! You've successfully authenticated, but GitHub does not provide shell access.</code></li>
</ul>
</section>
</section>
</section>
<section id="túnel-ssh-activo-y-configurado" class="level2 callout-success" data-number="A.6">
<h2 data-number="A.6" class="anchored" data-anchor-id="túnel-ssh-activo-y-configurado"><span class="header-section-number">A.6</span> ¡Túnel SSH Activo y Configurado!</h2>
<p>Has establecido una identidad digital segura entre tu equipo y GitHub. A partir de este momento, la comunicación para sincronizar tus repositorios será transparente y automática.</p>
<ul>
<li><strong>Identidad Permanente</strong>: Esta configuración se realiza <strong>una sola vez</strong> por computador; tu “firma digital” ya reside en el sistema.</li>
<li><strong>Adiós a las Interrupciones</strong>: GitHub ya no solicitará tu usuario, contraseña o tokens personales de acceso en cada operación.</li>
<li><strong>Compatibilidad Total</strong>: Esta llave es reconocida automáticamente por <strong>PowerShell</strong>, <strong>VS Code</strong>, <strong>Positron</strong>, <strong>RStudio</strong> y cualquier otra terminal científica que utilices.</li>
<li><strong>Seguridad de Grado Profesional</strong>: Tus envíos (<code>push</code>) viajan ahora por un canal cifrado bajo el estándar Ed25519.</li>
</ul>
</section>
<section id="sec-vinculacion-clase" class="level3">
<h3 class="anchored" data-anchor-id="sec-vinculacion-clase">Vinculación del Repositorio de Contenidos de la Clase</h3>
<p>Los contenidos de la clase están en <code>https://github.com/alexyshr/ProgramacionSIG2026.git</code> (HTTPS) o <code>git@github.com:alexyshr/ProgramacionSIG2026.git</code> (SSH). La elección de uno de estos dos protocolos (HTTPS o SSH), depende de si ha configurado su identidad digital, ver <a href="#sec-ssh-github" class="quarto-xref"><span>Section A.5.2</span></a>.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
¡Advertencia sobre la Estructura de Carpetas!
</div>
</div>
<div class="callout-body-container callout-body">
<p>Es fundamental para el orden del curso que el repositorio con los contenidos de la clase se conecte a una <strong>carpeta independiente</strong>.</p>
<p><strong>No sincronice estos archivos dentro de su carpeta local con los contenedores <code>ID UNAL</code></strong>. Mantener directorios separados garantiza que sus ejercicios personales y los materiales de lectura del profesor no se mezclen, evitando errores de sobreescritura y conflictos de Git al realizar actualizaciones del material.</p>
</div>
</div>
<section id="opción-a-sincronizar-mediante-ssh-recomendado" class="level4">
<h4 class="anchored" data-anchor-id="opción-a-sincronizar-mediante-ssh-recomendado">Opción A: Sincronizar mediante SSH (Recomendado)</h4>
<p>Utilice este método si ya configuró sus llaves siguiendo los pasos de la <a href="#sec-ssh-github" class="quarto-xref"><span>Section A.5.2</span></a>.</p>
<ul>
<li><p><strong>URL de la Clase</strong>: <code>git@github.com:alexyshr/ProgramacionSIG2026.git</code></p></li>
<li><p><strong>Vincular el repositorio remoto</strong>: Si ya inicializó su carpeta local (no la de sus contenedores Docker) con <code>git init</code>, ejecute el siguiente comando para establecer el origen:</p></li>
</ul>
<div class="sourceCode" id="cb27"><pre class="sourceCode powershell code-with-copy"><code class="sourceCode powershell"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>git remote add origin git@github<span class="op">.</span><span class="fu">com</span><span class="op">:</span>alexyshr<span class="op">/</span>ProgramacionSIG2026<span class="op">.</span><span class="fu">git</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<ul>
<li><strong>Descargar el contenido (Pull)</strong>: Para traer los archivos del servidor a su computadora por primera vez:</li>
</ul>
<div class="sourceCode" id="cb28"><pre class="sourceCode powershell code-with-copy"><code class="sourceCode powershell"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>git pull origin main</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<ul>
<li><strong>Verificación de estado</strong>: Confirme que la carpeta local está sincronizada correctamente:</li>
</ul>
<div class="sourceCode" id="cb29"><pre class="sourceCode powershell code-with-copy"><code class="sourceCode powershell"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>git status</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre><code>*Resultado esperado: `On branch main. Your branch is up to date. working tree clean.`*</code></pre>
</section>
</section>
<section id="opción-b-sincronizar-mediante-https" class="level3">
<h3 class="anchored" data-anchor-id="opción-b-sincronizar-mediante-https">Opción B: Sincronizar mediante HTTPS</h3>
<p>Utilice este método si aún no ha configurado llaves SSH o prefiere una descarga rápida. A diferencia del método anterior, este suele solicitar un <strong>Personal Access Token (PAT)</strong> (ver <span class="citation" data-cites="github-pat">(<a href="93-referencias.html#ref-github-pat" role="doc-biblioref"><strong>github-pat?</strong></a>)</span>) para realizar operaciones de subida (<em>push</em>).</p>
<ul>
<li><strong>URL de la Clase</strong>: <code>https://github.com/alexyshr/ProgramacionSIG2026.git</code></li>
<li><strong>Instrucción</strong>: Este comando descarga el repositorio completo y crea automáticamente una subcarpeta con el nombre del proyecto:</li>
</ul>
<div class="sourceCode" id="cb31"><pre class="sourceCode powershell code-with-copy"><code class="sourceCode powershell"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>git clone https<span class="op">://</span>github<span class="op">.</span><span class="fu">com</span><span class="op">/</span>alexyshr<span class="op">/</span>ProgramacionSIG2026<span class="op">.</span><span class="fu">git</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="notas-de-flujo-de-trabajo" class="level3">
<h3 class="anchored" data-anchor-id="notas-de-flujo-de-trabajo">Notas de Flujo de Trabajo</h3>
<ul>
<li><strong>Persistencia</strong>: Una vez clonado o vinculado el repositorio, Git recordará la ruta del servidor (ya sea SSH o HTTPS). No es necesario repetir los comandos de <code>remote add</code> o <code>clone</code> en sesiones futuras.</li>
<li><strong>Seguridad</strong>: Si opta por HTTPS, recuerde que GitHub ya no acepta contraseñas básicas por terminal; deberá generar un Token en la configuración de su cuenta. Por esta razón, se recomienda priorizar el uso de <strong>SSH</strong>.</li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Siguiente Paso
</div>
</div>
<div class="callout-body-container callout-body">
<p>Con el repositorio sincronizado y el contenedor de Docker activo (como se vio en la <a href="02-guia_instalacion_A_docker.html#sec-infraestructura" class="quarto-xref"><span>Section 2.2</span></a>), ya puede comenzar a trabajar en sus archivos <code>.qmd</code> y ver los cambios reflejados en tiempo real.</p>
</div>
</div>
</section>
<section id="vscode-ref" class="level2" data-number="A.7">
<h2 data-number="A.7" class="anchored" data-anchor-id="vscode-ref"><span class="header-section-number">A.7</span> Visual Studio Code: Extensiones e Interfaz</h2>
<section id="sec-command-palette" class="level3">
<h3 class="anchored" data-anchor-id="sec-command-palette">Atajos de Poder: La Paleta de Comandos</h3>
<p>La mayoría de las funciones avanzadas de VS Code no tienen un botón visible. Se acceden mediante la <strong>Paleta de Comandos</strong> presionando <code>Ctrl + Shift + P</code>. A continuación, los comandos más utilizados en este curso:</p>
<table class="table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Comando (Command Palette)</th>
<th style="text-align: left;">Propósito</th>
<th style="text-align: left;">¿Cuándo usarlo?</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong><code>Developer: Reload Window</code></strong></td>
<td style="text-align: left;">Reinicia la interfaz de VS Code sin cerrar el contenedor.</td>
<td style="text-align: left;">Cuando una extensión (como la de R o Julia) deja de responder.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong><code>Dev Containers: Rebuild Container</code></strong></td>
<td style="text-align: left;">Reconstruye la imagen desde el Dockerfile.</td>
<td style="text-align: left;">Cuando se realizan cambios en la configuración del entorno.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong><code>Quarto: Preview</code></strong></td>
<td style="text-align: left;">Abre una ventana lateral con la previsualización del documento.</td>
<td style="text-align: left;">Para ver los cambios en el <code>.qmd</code> en tiempo real.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong><code>R: Create R terminal</code></strong></td>
<td style="text-align: left;">Fuerza la apertura de una nueva consola de R vinculada.</td>
<td style="text-align: left;">Si el prompt <code>&gt;</code> no aparece automáticamente.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong><code>Julia: Start REPL</code></strong></td>
<td style="text-align: left;">Inicia la consola interactiva de Julia.</td>
<td style="text-align: left;">Al abrir el contenedor por primera vez para ejecutar código Julia.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong><code>Python: Select Interpreter</code></strong></td>
<td style="text-align: left;">Permite elegir la versión de Python del contenedor.</td>
<td style="text-align: left;">Si VS Code no detecta automáticamente <code>/usr/bin/python3</code>.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong><code>PostgreSQL: New Query</code></strong></td>
<td style="text-align: left;">Abre un editor SQL en blanco.</td>
<td style="text-align: left;">Para realizar consultas a la base de datos espacial.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong><code>Git: Pull</code> / <code>Git: Push</code></strong></td>
<td style="text-align: left;">Sincroniza cambios con GitHub.</td>
<td style="text-align: left;">Para actualizar el repositorio de la clase o subir tareas.</td>
</tr>
</tbody>
</table>
<hr>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
El comando de “Primer Auxilio”
</div>
</div>
<div class="callout-body-container callout-body">
<p>Si notas que el autocompletado desaparece o que los gráficos no cargan en <strong>httpgd</strong>, el primer paso siempre es ejecutar <strong><code>Developer: Reload Window</code></strong>. Esto refresca todas las conexiones de las extensiones con el contenedor sin interrumpir los procesos que Docker está ejecutando de fondo.</p>
</div>
</div>
<section id="atajos-de-teclado-rápidos" class="level4">
<h4 class="anchored" data-anchor-id="atajos-de-teclado-rápidos">Atajos de Teclado Rápidos</h4>
<p>Además de la paleta, memorice estos tres para su flujo diario: * <strong><code>Ctrl + Shift +</code> <code></code></strong> (acento grave): Abre una nueva Terminal. * <strong><code>Ctrl + Enter</code></strong>: Envía la línea de código actual desde el editor al REPL (R, Julia o Python). * <strong><code>Ctrl + Shift + V</code></strong>: Previsualiza archivos Markdown (.md) de forma rápida.</p>
</section>
</section>
<section id="sec-extensiones-vscode" class="level3">
<h3 class="anchored" data-anchor-id="sec-extensiones-vscode">Configuración de Extensiones en VS Code</h3>
<p>Para que el entorno de desarrollo sea plenamente funcional, es necesario instalar un conjunto de extensiones específicas. Una vez que haya realizado el proceso de <strong>“Attach to Running Container”</strong>, asegúrese de que estas herramientas estén instaladas <strong>dentro del contenedor</strong> (busque el botón azul <em>Install in Dev Container</em> en la pestaña de extensiones).</p>
<div id="tbl-extensiones" class="quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-extensiones-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;A.1: Extensiones de VS Code para el entorno de Geomática y Programación SIG
</figcaption>
<div aria-describedby="tbl-extensiones-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Categoría</th>
<th style="text-align: left;">Herramienta</th>
<th style="text-align: left;">Propósito</th>
<th style="text-align: left;">ID de la Extensión</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Infraestructura</strong></td>
<td style="text-align: left;"><strong>Dev Containers</strong></td>
<td style="text-align: left;">Conexión y gestión del contenedor activo</td>
<td style="text-align: left;"><code>ms-vscode-remote.remote-containers</code></td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;"><strong>Docker / Container Tools</strong></td>
<td style="text-align: left;">Control de imágenes y recursos del contenedor</td>
<td style="text-align: left;"><code>ms-azuretools.vscode-docker</code></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Ecosistema R</strong></td>
<td style="text-align: left;"><strong>R (REditorSupport)</strong></td>
<td style="text-align: left;">Soporte de sintaxis, LSP y terminal de R</td>
<td style="text-align: left;"><code>REditorSupport.r</code></td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;"><strong>R Debugger &amp; Tools</strong></td>
<td style="text-align: left;">Depuración de scripts y herramientas de desarrollo</td>
<td style="text-align: left;"><code>RDebugger.r-debugger</code></td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;"><strong>R Extension Pack</strong></td>
<td style="text-align: left;">Pack de utilidades (por Yuki Ueda)</td>
<td style="text-align: left;"><code>yukiueda.r-extension-pack</code></td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Ecosistema Python</strong></td>
<td style="text-align: left;"><strong>Python (Microsoft)</strong></td>
<td style="text-align: left;">IntelliSense (Pylance) y depuración avanzada</td>
<td style="text-align: left;"><code>ms-python.python</code></td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;"><strong>Python Debugger</strong></td>
<td style="text-align: left;">Motor de depuración específico para Python</td>
<td style="text-align: left;"><code>ms-python.debugpy</code></td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;"><strong>Jupyter (Microsoft)</strong></td>
<td style="text-align: left;">Soporte para Notebooks e interactividad nativa</td>
<td style="text-align: left;"><code>ms-toolsai.jupyter</code></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Ecosistema Julia</strong></td>
<td style="text-align: left;"><strong>Julia</strong></td>
<td style="text-align: left;">Soporte integral para ejecución y gráficos</td>
<td style="text-align: left;"><code>julialang.language-julia</code></td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Base de Datos</strong></td>
<td style="text-align: left;"><strong>PostgreSQL</strong></td>
<td style="text-align: left;">Cliente para explorar la DB (Chris Kolkman)</td>
<td style="text-align: left;"><code>ckolkman.vscode-postgres</code></td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;"><strong>psql</strong></td>
<td style="text-align: left;">Herramienta de consulta SQL (doublefint)</td>
<td style="text-align: left;"><code>doublefint.psql</code></td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Publicación</strong></td>
<td style="text-align: left;"><strong>Quarto</strong></td>
<td style="text-align: left;">Renderizado y preview de archivos <code>.qmd</code></td>
<td style="text-align: left;"><code>quarto.quarto</code></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Versión</strong></td>
<td style="text-align: left;"><strong>GitHub Repositories</strong></td>
<td style="text-align: left;">Manejo de archivos remotos sin clonar todo</td>
<td style="text-align: left;"><code>github.remotehub</code></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<hr>
<section id="notas-sobre-herramientas-específicas" class="level4">
<h4 class="anchored" data-anchor-id="notas-sobre-herramientas-específicas">Notas sobre herramientas específicas</h4>
<ul>
<li><strong>PostgreSQL (Chris Kolkman)</strong>: Esta extensión le permitirá conectarse a la base de datos espacial del contenedor sin salir de VS Code. Podrá ejecutar queries SQL y visualizar tablas directamente.</li>
<li><strong>Jupyter Ecosystem</strong>: Incluimos el <em>Jupyter Keymap</em> para aquellos acostumbrados a los atajos de teclado de Jupyter Notebooks. Esto facilita la transición al trabajar con kernels de Python dentro de Quarto.</li>
<li><strong>Sobre <code>psql</code></strong>: La herramienta de línea de comandos <code>psql</code> ya viene preinstalada <strong>dentro del sistema operativo del contenedor</strong> (PostgreSQL Client). No requiere una extensión adicional para funcionar en la terminal.</li>
</ul>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Instalación Local vs.&nbsp;Remota
</div>
</div>
<div class="callout-body-container callout-body">
<p>Recuerde que extensiones como <strong>Dev Containers</strong> y <strong>Docker</strong> deben estar instaladas en su VS Code <strong>local</strong> (en Windows), mientras que las de análisis (R, Python, Julia, PostgreSQL) deben estar instaladas <strong>dentro de la sesión del contenedor</strong> para acceder a los compiladores y librerías de la imagen.</p>
</div>
</div>
<hr>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Soporte del Lenguaje en R
</div>
</div>
<div class="callout-body-container callout-body">
<p>Para que el autocompletado y la documentación en tiempo real funcionen, el contenedor requiere el paquete <code>languageserver</code>. Aunque la imagen ya lo incluye por defecto, si nota que el resaltado de sintaxis falla, puede reinstalarlo ejecutando: <code>install.packages("languageserver")</code> en su consola de R.</p>
</div>
</div>
<hr>
</section>
</section>
<section id="verificación-de-conectividad" class="level3">
<h3 class="anchored" data-anchor-id="verificación-de-conectividad">Verificación de Conectividad</h3>
<p>Una vez instaladas las extensiones, verifique que su entorno esté correctamente configurado siguiendo estos puntos:</p>
<ul>
<li><strong>Estado del Contenedor</strong>: En la esquina inferior izquierda de VS Code, debe aparecer un recuadro azul con el texto: <strong>Dev Container: contenedor_sig_unal</strong>.</li>
<li><strong>Activación de Kernels</strong>: Al abrir un archivo <code>.qmd</code>, en la esquina superior derecha debe poder seleccionar el kernel deseado (R, Python 3 o Julia).</li>
<li><strong>Terminal Unificada</strong>: Al abrir una nueva terminal (<code>Ctrl + Shift +</code> <code></code>), la línea de comandos debe estar identificada como <code>rstudio@contenedor_sig_unal:/home/rstudio/work$</code>.</li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Sincronización Automática
</div>
</div>
<div class="callout-body-container callout-body">
<p>Recuerde que cualquier cambio que realice en la configuración de estas extensiones mientras esté conectado al contenedor se guardará en su perfil local de VS Code, facilitando las conexiones futuras.</p>
</div>
</div>
</section>
</section>
<section id="shortcuts-ref" class="level2" data-number="A.8">
<h2 data-number="A.8" class="anchored" data-anchor-id="shortcuts-ref"><span class="header-section-number">A.8</span> Comandos Rápidos y Shortcuts</h2>
<section id="jupyter-notebook-dentro-de-vscode" class="level3">
<h3 class="anchored" data-anchor-id="jupyter-notebook-dentro-de-vscode">Jupyter Notebook (Dentro de VSCode)</h3>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;">Acción</th>
<th style="text-align: left;">Atajo (Esc Mode)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Ejecutar Celda</td>
<td style="text-align: left;"><code>Ctrl + Enter</code></td>
</tr>
<tr class="even">
<td style="text-align: left;">Ejecutar y pasar a la siguiente</td>
<td style="text-align: left;"><code>Shift + Enter</code></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Convertir a Markdown</td>
<td style="text-align: left;"><code>M</code></td>
</tr>
<tr class="even">
<td style="text-align: left;">Convertir a Código</td>
<td style="text-align: left;"><code>Y</code></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Crear celda arriba / abajo</td>
<td style="text-align: left;"><code>A</code> / <code>B</code></td>
</tr>
</tbody>
</table>
</section>
<section id="comandos-de-windows-powershellcmd" class="level3">
<h3 class="anchored" data-anchor-id="comandos-de-windows-powershellcmd">Comandos de Windows (PowerShell/CMD)</h3>
<ul>
<li><strong>Ver uso de RAM:</strong> <code>Get-Process | Sort-Object WorkingSet -Descending | Select-Object -First 10</code></li>
<li><strong>Ver estado de WSL:</strong> <code>wsl --list --verbose</code></li>
<li><strong>Limpiar Cache de DNS:</strong> <code>ipconfig /flushdns</code></li>
</ul>
</section>
</section>
<section id="adicionales-sobre-python" class="level2" data-number="A.9">
<h2 data-number="A.9" class="anchored" data-anchor-id="adicionales-sobre-python"><span class="header-section-number">A.9</span> Adicionales Sobre Python</h2>
<section id="versiones-instaladas-del-software" class="level3">
<h3 class="anchored" data-anchor-id="versiones-instaladas-del-software">Versiones Instaladas del Software</h3>
<p>Para verificar las versiones instaladas, puede ejecutar <code>pip3 list</code> en la terminal. Las versiones instaladas deben coincidir con la siguiente tabla:</p>
<table class="table">
<colgroup>
<col style="width: 10%">
<col style="width: 15%">
<col style="width: 10%">
<col style="width: 26%">
<col style="width: 36%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Software</th>
<th style="text-align: left;">Tipo</th>
<th style="text-align: left;">Versión</th>
<th style="text-align: left;">Comando (desde terminal)</th>
<th style="text-align: left;">Comando (desde Python)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><code>Python</code></td>
<td style="text-align: left;">Lenguaje</td>
<td style="text-align: left;">3.12.3</td>
<td style="text-align: left;"><code>python3 --version</code></td>
<td style="text-align: left;"><code>import sys; sys.version</code></td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>pip</code></td>
<td style="text-align: left;">Gestor de paquetes</td>
<td style="text-align: left;">24.0</td>
<td style="text-align: left;"><code>pip3 --version</code></td>
<td style="text-align: left;"><code>import pip; pip.__version__</code></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>numpy</code></td>
<td style="text-align: left;">Paquete</td>
<td style="text-align: left;">2.4.1</td>
<td style="text-align: left;"><code>pip3 show numpy</code></td>
<td style="text-align: left;"><code>import numpy; numpy.__version__</code></td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>pandas</code></td>
<td style="text-align: left;">Paquete</td>
<td style="text-align: left;">2.3.3</td>
<td style="text-align: left;"><code>pip3 show pandas</code></td>
<td style="text-align: left;"><code>import pandas; pandas.__version__</code></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>geopandas</code></td>
<td style="text-align: left;">Paquete</td>
<td style="text-align: left;">1.1.2</td>
<td style="text-align: left;"><code>pip3 show geopandas</code></td>
<td style="text-align: left;"><code>import geopandas; geopandas.__version__</code></td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>shapely</code></td>
<td style="text-align: left;">Paquete</td>
<td style="text-align: left;">2.1.2</td>
<td style="text-align: left;"><code>pip3 show shapely</code></td>
<td style="text-align: left;"><code>import shapely; shapely.__version__</code></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>pyproj</code></td>
<td style="text-align: left;">Paquete</td>
<td style="text-align: left;">3.7.2</td>
<td style="text-align: left;"><code>pip3 show pyproj</code></td>
<td style="text-align: left;"><code>import pyproj; pyproj.__version__</code></td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>fiona</code></td>
<td style="text-align: left;">Paquete</td>
<td style="text-align: left;">1.10.1</td>
<td style="text-align: left;"><code>pip3 show fiona</code></td>
<td style="text-align: left;"><code>import fiona; fiona.__version__</code></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>rasterio</code></td>
<td style="text-align: left;">Paquete</td>
<td style="text-align: left;">1.5.0</td>
<td style="text-align: left;"><code>pip3 show rasterio</code></td>
<td style="text-align: left;"><code>import rasterio; rasterio.__version__</code></td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="adicionales-sobre-r" class="level2" data-number="A.10">
<h2 data-number="A.10" class="anchored" data-anchor-id="adicionales-sobre-r"><span class="header-section-number">A.10</span> Adicionales Sobre R</h2>
<section id="versiones-instaladas-del-software-1" class="level3">
<h3 class="anchored" data-anchor-id="versiones-instaladas-del-software-1">Versiones Instaladas del Software</h3>
<p>Versiones que deben quedar instaladas en el sistema R:</p>
<table class="table">
<colgroup>
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 30%">
<col style="width: 43%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Software</th>
<th style="text-align: left;">Tipo</th>
<th style="text-align: left;">Versión</th>
<th style="text-align: left;">Comando (desde terminal)</th>
<th style="text-align: left;">Comando (desde R)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><code>R</code></td>
<td style="text-align: left;">Lenguaje</td>
<td style="text-align: left;">4.5.2</td>
<td style="text-align: left;"><code>R --version</code></td>
<td style="text-align: left;"><code>R.version.string</code></td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>GEOS</code></td>
<td style="text-align: left;">Librería sistema</td>
<td style="text-align: left;">3.12.1</td>
<td style="text-align: left;"><code>geos-config --version</code></td>
<td style="text-align: left;"><code>sf::sf_extSoftVersion()["GEOS"]</code></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>GDAL</code></td>
<td style="text-align: left;">Librería sistema</td>
<td style="text-align: left;">3.8.4</td>
<td style="text-align: left;"><code>gdalinfo --version</code></td>
<td style="text-align: left;"><code>sf::sf_extSoftVersion()["GDAL"]</code></td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>PROJ</code></td>
<td style="text-align: left;">Librería sistema</td>
<td style="text-align: left;">9.4.0</td>
<td style="text-align: left;">(no aplica / no disponible)</td>
<td style="text-align: left;"><code>sf::sf_extSoftVersion()["PROJ"]</code></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>sf</code></td>
<td style="text-align: left;">Paquete</td>
<td style="text-align: left;">1.0.23</td>
<td style="text-align: left;"><code>R -q -e "packageVersion('sf')"</code></td>
<td style="text-align: left;"><code>packageVersion("sf")</code></td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>terra</code></td>
<td style="text-align: left;">Paquete</td>
<td style="text-align: left;">1.8.86</td>
<td style="text-align: left;"><code>R -q -e "packageVersion('terra')"</code></td>
<td style="text-align: left;"><code>packageVersion("terra")</code></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>stars</code></td>
<td style="text-align: left;">Paquete</td>
<td style="text-align: left;">0.7.0</td>
<td style="text-align: left;"><code>R -q -e "packageVersion('stars')"</code></td>
<td style="text-align: left;"><code>packageVersion("stars")</code></td>
</tr>
</tbody>
</table>
</section>
<section id="sec-httpgd-config" class="level3">
<h3 class="anchored" data-anchor-id="sec-httpgd-config">Visualización Interactiva con <code>httpgd</code></h3>
<p>Dado que nuestro entorno Docker es “headless” (sin monitor propio), utilizamos <strong><code>httpgd</code></strong> como un servidor gráfico intermedio. Este paquete captura las señales de dibujo de R y las sirve a través de una URL que VS Code puede renderizar.</p>
<section id="inicio-del-servidor-gráfico" class="level4">
<h4 class="anchored" data-anchor-id="inicio-del-servidor-gráfico">1. Inicio del Servidor Gráfico</h4>
<p>Cada vez que inicie una nueva sesión de R, debe despertar al servidor manualmente:</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Inicia el motor gráfico</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>httpgd<span class="sc">::</span><span class="fu">hgd</span>()</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Verifica el estado y el puerto asignado</span></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>httpgd<span class="sc">::</span><span class="fu">hgd_details</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="resolución-de-conflictos-el-fix-del-puerto" class="level4">
<h4 class="anchored" data-anchor-id="resolución-de-conflictos-el-fix-del-puerto">2. Resolución de Conflictos (El “Fix” del Puerto)</h4>
<p>En nuestro contenedor, el puerto estándar para gráficos está mapeado al <strong>8787</strong>. Si al ejecutar <code>hgd_details()</code> nota que el sistema asignó un puerto aleatorio o si el visor aparece en blanco, fuerce la conexión con la siguiente “receta”:</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Forzar host y puerto para compatibilidad con Docker</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>httpgd<span class="sc">::</span><span class="fu">hgd</span>(<span class="at">host =</span> <span class="st">"0.0.0.0"</span>, <span class="at">port =</span> <span class="dv">8787</span>, <span class="at">token =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<hr>
</section>
<section id="formas-de-ver-sus-gráficos" class="level4">
<h4 class="anchored" data-anchor-id="formas-de-ver-sus-gráficos">3. Formas de ver sus Gráficos</h4>
<p>Una vez el servidor está corriendo, tiene dos caminos para visualizar sus mapas:</p>
<table class="table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Método</th>
<th style="text-align: left;">Comando / Acción</th>
<th style="text-align: left;">Ventaja</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Visor Interno</strong></td>
<td style="text-align: left;"><code>Ctrl + Shift + P</code> -&gt; <strong>Open httpgd viewer</strong></td>
<td style="text-align: left;">Mantiene todo dentro de una pestaña de VS Code.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Navegador Externo</strong></td>
<td style="text-align: left;"><code>httpgd::hgd_browse()</code></td>
<td style="text-align: left;">Ideal si trabaja con dos monitores para ver mapas en pantalla completa.</td>
</tr>
</tbody>
</table>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
¿Por qué <code>token = FALSE</code>?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Dentro del entorno seguro del contenedor, desactivamos el <em>token</em> para facilitar la conexión inmediata entre el servidor de R y el visor de VS Code sin que el firewall interno bloquee la petición por falta de credenciales.</p>
</div>
</div>
<hr>
</section>
<section id="verificación-de-salud" class="level4">
<h4 class="anchored" data-anchor-id="verificación-de-salud">4. Verificación de Salud</h4>
<p>Si después de iniciar el servidor intenta graficar algo (ej: <code>plot(1:10)</code>) y no ve nada, ejecute <code>httpgd::hgd_details()</code>. Asegúrese de que: 1. <strong>URL</strong>: Apunte a <code>http://0.0.0.0:8787</code>. 2. <strong>Status</strong>: Indique que está escuchando (<em>listening</em>).</p>
</section>
</section>
<section id="sec-repl-concept" class="level3">
<h3 class="anchored" data-anchor-id="sec-repl-concept">El Entorno Interactivo (REPL) y Motores Gráficos</h3>
<p>En el desarrollo científico, el <strong>REPL</strong> (<em>Read-Eval-Print Loop</em>) es la consola interactiva que permite la “programación exploratoria”. Es el ciclo donde el sistema <strong>lee</strong> su instrucción, la <strong>evalúa</strong> mediante el motor correspondiente, <strong>imprime</strong> el resultado y queda en un <strong>bucle</strong> a la espera del siguiente comando.</p>
<p>En nuestro laboratorio políglota, la identidad visual del REPL es su brújula para saber en qué lenguaje está operando:</p>
<table class="table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Lenguaje</th>
<th style="text-align: left;">¿Cómo se ve el REPL?</th>
<th style="text-align: left;">Características en este curso</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>R</strong></td>
<td style="text-align: left;"><code>&gt;</code></td>
<td style="text-align: left;">Consola estándar para procesos geoespaciales con <code>sf</code> o <code>terra</code>.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Julia</strong></td>
<td style="text-align: left;"><code>julia&gt;</code></td>
<td style="text-align: left;">Entorno de alto rendimiento con modos de ayuda (<code>?</code>) y terminal (<code>;</code>).</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Python</strong></td>
<td style="text-align: left;"><code>&gt;&gt;&gt;</code></td>
<td style="text-align: left;">Consola básica; se recomienda el uso de <strong>IPython</strong> para interactividad.</td>
</tr>
</tbody>
</table>
<p>La experiencia interactiva y el soporte gráfico dentro de <strong>VS Code</strong> dependen de la combinación entre el motor de ejecución y el dispositivo gráfico configurado en el contenedor:</p>
<table class="table">
<colgroup>
<col style="width: 19%">
<col style="width: 19%">
<col style="width: 19%">
<col style="width: 19%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Lenguaje</th>
<th style="text-align: left;">Acceso / Contexto</th>
<th style="text-align: left;">Motor de Ejecución</th>
<th style="text-align: left;">Dispositivo Gráfico</th>
<th style="text-align: center;">Soporte Inline</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>R</strong></td>
<td style="text-align: left;">Nativo (Estático)</td>
<td style="text-align: left;">R Extension</td>
<td style="text-align: left;">VS Code Plots (Pane)</td>
<td style="text-align: center;">✅</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>R</strong></td>
<td style="text-align: left;">Nativo (Interactivo)</td>
<td style="text-align: left;">R Extension</td>
<td style="text-align: left;"><strong>httpgd</strong></td>
<td style="text-align: center;">✅</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Julia</strong></td>
<td style="text-align: left;">Nativo (REPL)</td>
<td style="text-align: left;">VSCodeServer</td>
<td style="text-align: left;">VS Code Plots (Pane)</td>
<td style="text-align: center;">✅</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Julia</strong></td>
<td style="text-align: left;">Interop (R-Bridge)</td>
<td style="text-align: left;"><code>JuliaConnectoR</code></td>
<td style="text-align: left;"><strong>httpgd</strong> (vía R)</td>
<td style="text-align: center;">✅</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Python</strong></td>
<td style="text-align: left;">Interop (R-Bridge)</td>
<td style="text-align: left;"><code>reticulate</code></td>
<td style="text-align: left;">R Device (<strong>httpgd</strong>)</td>
<td style="text-align: center;">❌ / ⚠️</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Python</strong></td>
<td style="text-align: left;">Nativo (Jupyter)</td>
<td style="text-align: left;">Jupyter kernel</td>
<td style="text-align: left;">Jupyter Viewer</td>
<td style="text-align: center;">✅</td>
</tr>
</tbody>
</table>
<section id="el-rol-crítico-de-httpgd-en-r" class="level4">
<h4 class="anchored" data-anchor-id="el-rol-crítico-de-httpgd-en-r">El rol crítico de <code>httpgd</code> en R</h4>
<p>Para R, no basta con tener la extensión instalada. El paquete <strong><code>httpgd</code></strong> actúa como un servidor web interno que captura los gráficos generados en el contenedor y los “proyecta” en VS Code.</p>
<ul>
<li><strong>¿Por qué lo usamos?</strong> Los dispositivos gráficos tradicionales (como <code>X11</code> o <code>windows()</code>) no funcionan dentro de un contenedor Docker (<em>headless</em>). <code>httpgd</code> soluciona esto convirtiendo cada mapa en un elemento interactivo SVG/HTML renderizable.</li>
<li><strong>Activación</strong>: Siempre debe iniciar su sesión de R ejecutando <code>httpgd::hgd()</code> para abrir este canal de comunicación.</li>
</ul>
<hr>
</section>
</section>
<section id="sec-interoperabilidad" class="level3">
<h3 class="anchored" data-anchor-id="sec-interoperabilidad">Paquetes para Comunicación con Julia y Python</h3>
<p>Para que este ecosistema funcione, R actúa como el “director de orquesta” utilizando un motor de ejecución y una serie de puentes que permiten la comunicación fluida de datos entre lenguajes.</p>
<table class="table">
<colgroup>
<col style="width: 23%">
<col style="width: 23%">
<col style="width: 23%">
<col style="width: 29%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Lenguaje / Función</th>
<th style="text-align: left;">Paquete en R</th>
<th style="text-align: left;">Motor / Propósito</th>
<th style="text-align: center;">Estado</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Renderizado</strong></td>
<td style="text-align: left;"><strong><code>knitr</code></strong></td>
<td style="text-align: left;">Motor maestro que orquesta la ejecución de celdas en el documento</td>
<td style="text-align: center;">✅</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Julia</strong></td>
<td style="text-align: left;"><code>JuliaConnectoR</code></td>
<td style="text-align: left;">Comunicación funcional estable con el kernel de Julia</td>
<td style="text-align: center;">✅</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Python</strong></td>
<td style="text-align: left;"><code>reticulate</code></td>
<td style="text-align: left;">Interoperabilidad de objetos y ejecución de Python</td>
<td style="text-align: center;">✅</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>LSP (Soporte)</strong></td>
<td style="text-align: left;"><code>languageserver</code></td>
<td style="text-align: left;">Autocompletado, IntelliSense y ayuda en tiempo real</td>
<td style="text-align: center;">✅</td>
</tr>
</tbody>
</table>
<section id="el-rol-de-knitr" class="level4">
<h4 class="anchored" data-anchor-id="el-rol-de-knitr">El Rol de <code>knitr</code></h4>
<p>Mientras que los paquetes actúan como puentes técnicos, <strong><code>knitr</code></strong> es el encargado de leer el archivo <code>.qmd</code>, enviar las instrucciones a los motores respectivos y capturar los resultados (tablas, mapas, gráficos) para integrarlos en el documento final. Sin <code>knitr</code>, la integración políglota de Quarto no sería posible.</p>
</section>
<section id="transición-técnica-de-juliacall-a-juliaconnector" class="level4">
<h4 class="anchored" data-anchor-id="transición-técnica-de-juliacall-a-juliaconnector">Transición Técnica: De <code>JuliaCall</code> a <code>JuliaConnectoR</code></h4>
<p>En el diseño de este entorno, se tomó la decisión técnica de descartar el paquete <code>JuliaCall</code> en favor de <strong><code>JuliaConnectoR</code></strong>:</p>
<ol type="1">
<li><strong>El Problema</strong>: <code>JuliaCall</code> presentaba inestabilidades al gestionar dependencias dinámicas compartidas (como <code>libcurl</code> o <code>libstdc++</code>) dentro del contenedor, causando cierres inesperados (<em>crashes</em>) de la sesión de R.</li>
<li><strong>La Sustitución</strong>: Se seleccionó <strong><code>JuliaConnectoR</code></strong> por su arquitectura más limpia, que no interfiere con el entorno de Julia ya configurado en el sistema operativo.</li>
<li><strong>La Solución</strong>: La integración se resolvió mediante una “inyección” de código en el archivo <code>Rprofile.site</code>, configurando automáticamente la ruta del ejecutable en <code>$Sys.BINDIR$</code> y definiendo las funciones maestras <strong><code>j_eval()</code></strong> y <strong><code>j_plot()</code></strong>.</li>
</ol>
<hr>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
🧠 Regla de Oro del Curso
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li><strong>Julia y R</strong>: Se operan de manera totalmente <strong>interactiva</strong> en VS Code (envío de líneas con <code>Ctrl+Enter</code>).</li>
<li><strong>Python vía reticulate</strong>: Se utiliza primordialmente para el <strong>renderizado (vía knitr)</strong> de informes finales. Para una programación interactiva pura en Python, se recomienda el uso de los <strong>Jupyter kernels</strong>.</li>
</ol>
</div>
</div>
</section>
</section>
</section>
<section id="adicionales-sobre-julia" class="level2" data-number="A.11">
<h2 data-number="A.11" class="anchored" data-anchor-id="adicionales-sobre-julia"><span class="header-section-number">A.11</span> Adicionales Sobre Julia</h2>
<section id="versiones-instaladas-del-software-2" class="level3">
<h3 class="anchored" data-anchor-id="versiones-instaladas-del-software-2">Versiones Instaladas del Software</h3>
<p>Versiones de paquetes <code>Julia</code> en el sistema:</p>
<table class="table">
<colgroup>
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 40%">
<col style="width: 30%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Software</th>
<th style="text-align: left;">Tipo</th>
<th style="text-align: left;">Versión</th>
<th style="text-align: left;">Comando (desde terminal)</th>
<th style="text-align: left;">Comando (desde Julia)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><code>Julia</code></td>
<td style="text-align: left;">Lenguaje</td>
<td style="text-align: left;">1.10.4</td>
<td style="text-align: left;"><code>julia --version</code></td>
<td style="text-align: left;"><code>VERSION</code></td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>LibPQ</code></td>
<td style="text-align: left;">Paquete</td>
<td style="text-align: left;">1.18.0</td>
<td style="text-align: left;"><code>julia -e "using LibPQ; println(pkgversion(LibPQ))"</code></td>
<td style="text-align: left;"><code>using LibPQ; pkgversion(LibPQ)</code></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>ArchGDAL</code></td>
<td style="text-align: left;">Paquete</td>
<td style="text-align: left;">0.10.11</td>
<td style="text-align: left;"><code>julia -e "using ArchGDAL; println(pkgversion(ArchGDAL))"</code></td>
<td style="text-align: left;"><code>using ArchGDAL; pkgversion(ArchGDAL)</code></td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>LibGEOS</code></td>
<td style="text-align: left;">Paquete</td>
<td style="text-align: left;">0.9.7</td>
<td style="text-align: left;"><code>julia -e "using LibGEOS; println(pkgversion(LibGEOS))"</code></td>
<td style="text-align: left;"><code>using LibGEOS; pkgversion(LibGEOS)</code></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>Plots</code></td>
<td style="text-align: left;">Paquete</td>
<td style="text-align: left;">1.41.4</td>
<td style="text-align: left;"><code>julia -e "using Plots; println(pkgversion(Plots))"</code></td>
<td style="text-align: left;"><code>using Plots; pkgversion(Plots)</code></td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>DataFrames</code></td>
<td style="text-align: left;">Paquete</td>
<td style="text-align: left;">1.8.1</td>
<td style="text-align: left;"><code>julia -e "using DataFrames; println(pkgversion(DataFrames))"</code></td>
<td style="text-align: left;"><code>using DataFrames; pkgversion(DataFrames)</code></td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="sec-comandos-so" class="level2" data-number="A.12">
<h2 data-number="A.12" class="anchored" data-anchor-id="sec-comandos-so"><span class="header-section-number">A.12</span> Comandos de Terminal (Sistema Operativo)</h2>
<p>Al trabajar dentro de un contenedor Docker, la terminal es su línea directa con el sistema operativo (Ubuntu/Debian). Estos comandos le permitirán verificar que los motores geoespaciales y las librerías de sistema están correctamente instalados.</p>
<table class="table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Comando</th>
<th style="text-align: left;">Propósito</th>
<th style="text-align: left;">¿Para qué sirve en el curso?</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><code>dpkg -l \| grep -E "libpng\|libgdal\|libproj\|libgeos"</code></td>
<td style="text-align: left;">Lista librerías instaladas</td>
<td style="text-align: left;">Verificar que los drivers de mapas (GDAL, PROJ, GEOS) están activos.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>gdalinfo --version</code></td>
<td style="text-align: left;">Versión de GDAL</td>
<td style="text-align: left;">Confirmar que el motor de traducción de datos geográficos funciona.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>df -h</code></td>
<td style="text-align: left;">Espacio en disco</td>
<td style="text-align: left;">Evitar errores de “Disk Full” al descargar imágenes satelitales pesadas.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>htop</code> (o <code>top</code>)</td>
<td style="text-align: left;">Monitor de recursos</td>
<td style="text-align: left;">Ver si un proceso de Julia o R está consumiendo toda la RAM o CPU.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>ls -la</code></td>
<td style="text-align: left;">Listado detallado</td>
<td style="text-align: left;">Revisar permisos de archivos y carpetas (clave para errores de Git).</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>psql --version</code></td>
<td style="text-align: left;">Versión de Postgres</td>
<td style="text-align: left;">Confirmar que el cliente de base de datos está listo para usarse.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>which r</code> / <code>which julia</code></td>
<td style="text-align: left;">Ruta del ejecutable</td>
<td style="text-align: left;">Localizar dónde están instalados los lenguajes para configurar el Path.</td>
</tr>
</tbody>
</table>
<hr>
<section id="verificación-de-librerías-geoespaciales" class="level3">
<h3 class="anchored" data-anchor-id="verificación-de-librerías-geoespaciales">Verificación de Librerías Geoespaciales</h3>
<p>El comando <code>dpkg -l | grep -E "libpng|libgdal|libproj|libgeos"</code> es su principal herramienta de diagnóstico. Si al ejecutarlo no obtiene resultados, las funciones de mapeo en R (<code>sf</code>), Python (<code>geopandas</code>) y Julia (<code>ArchGDAL</code>) fallarán, ya que todas dependen de estos binarios del sistema.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip de Productividad
</div>
</div>
<div class="callout-body-container callout-body">
<p>En la terminal de VS Code, puede usar la tecla <strong>Tab</strong> para autocompletar nombres de archivos o comandos, y las <strong>flechas arriba/abajo</strong> para navegar por el historial de comandos ejecutados.</p>
</div>
</div>
<section id="cómo-leer-la-salida-de-dpkg" class="level4">
<h4 class="anchored" data-anchor-id="cómo-leer-la-salida-de-dpkg">¿Cómo leer la salida de <code>dpkg</code>?</h4>
<p>Al ejecutar el comando de verificación, verá una lista con el prefijo <code>ii</code>. Esto significa: * <strong>i</strong>: <em>Desired state</em> (Install) * <strong>i</strong>: <em>Current state</em> (Installed)</p>
<p>Si ve algo diferente a <code>ii</code>, el paquete tiene problemas de instalación.</p>
<hr>
</section>
</section>
</section>
<section id="sec-openssl-surgery" class="level2" data-number="A.13">
<h2 data-number="A.13" class="anchored" data-anchor-id="sec-openssl-surgery"><span class="header-section-number">A.13</span> La Cirugía de Librerías: El “Cambiazo” de OpenSSL</h2>
<p>Al trabajar con contenedores de última generación, a veces nos encontramos con un choque de versiones entre lo que el sistema operativo ofrece y lo que los lenguajes de programación esperan. En nuestro caso, realizamos una “cirugía” técnica utilizando enlaces simbólicos (<code>ln -sf</code>).</p>
<section id="el-conflicto-3.0.x-o-3.3.x" class="level3">
<h3 class="anchored" data-anchor-id="el-conflicto-3.0.x-o-3.3.x">1. El Conflicto: ¿3.0.x o 3.3.x?</h3>
<p>La respuesta corta es: <strong>Físicamente tiene instalada la versión 3.0.x, pero le mentimos al software diciéndole que es la 3.3.x.</strong></p>
<ul>
<li><strong>La Realidad (Sistema)</strong>: Su contenedor corre sobre <strong>Ubuntu 24.04 (Noble Numbat)</strong>. Esta versión viene de fábrica con <strong>OpenSSL 3.0.x</strong>, que es la versión estable y oficial del sistema.</li>
<li><strong>La Expectativa (Julia)</strong>: Algunos paquetes potentes de Julia (como los binarios JLL de <code>GDAL</code> o <code>NCDatasets</code>) fueron compilados en entornos más recientes que ya usaban <strong>OpenSSL 3.3.x</strong>.</li>
</ul>
<p>Cuando Julia intenta arrancar, busca una “etiqueta” interna llamada <code>OPENSSL_3.3.0</code>. Al no encontrarla en la librería de Ubuntu, el sistema lanza un error y bloquea la carga de mapas.</p>
</section>
<section id="la-solución-qué-hace-exactamente-ln--sf" class="level3">
<h3 class="anchored" data-anchor-id="la-solución-qué-hace-exactamente-ln--sf">2. La Solución: ¿Qué hace exactamente <code>ln -sf</code>?</h3>
<p>Imagine que Julia es un guardia de seguridad que busca una llave maestra etiquetada como <strong>“Llave 3.3”</strong>. Al revisar la caja fuerte (el sistema), solo ve la <strong>“Llave 3.0”</strong> y se niega a abrir. Lo que hicimos fue un “cambiazo” estratégico.</p>
<p>Ejecutamos este comando de “cirugía”:</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">find</span> /root/.julia/artifacts <span class="at">-name</span> <span class="st">"libssl.so*"</span> <span class="at">-exec</span> ln <span class="at">-sf</span> /usr/lib/x86_64-linux-gnu/libssl.so.3 {} <span class="dt">\;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><strong>Desglose de la operación:</strong> 1. <strong><code>find ... -name "libssl.so*"</code></strong>: Localiza todos los archivos de librería que Julia descargó por su cuenta (sus propios binarios internos). 2. <strong><code>-exec ln -sf ... {}</code></strong>: Por cada archivo encontrado, borra el original (la <code>-f</code> de <em>force</em>) y crea un <strong>enlace simbólico</strong> (la <code>-s</code> de <em>symbolic</em>). 3. <strong>El Destino</strong>: El enlace apunta directamente a la librería real de Ubuntu (<code>/usr/lib/.../libssl.so.3</code>).</p>
</section>
<section id="por-qué-funciona-si-las-versiones-son-distintas" class="level3">
<h3 class="anchored" data-anchor-id="por-qué-funciona-si-las-versiones-son-distintas">3. ¿Por qué funciona si las versiones son distintas?</h3>
<p>Funciona gracias a que <strong>OpenSSL 3</strong> mantiene algo llamado <strong>compatibilidad binaria</strong> entre sus versiones menores. Las funciones internas se llaman exactamente igual; lo único que cambió fue el “nombre del archivo” que Julia buscaba.</p>
<p>Al redirigir el nombre, Julia utiliza la librería de Ubuntu pensando que es la suya, y como las instrucciones internas son compatibles, el sistema arranca sin errores y con total estabilidad.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Importancia para el SIG
</div>
</div>
<div class="callout-body-container callout-body">
<p>Sin esta cirugía, paquetes como <code>ArchGDAL</code> en Julia no podrían cargar los controladores para leer archivos <code>.tif</code> o conectarse a bases de datos espaciales, ya que la comunicación segura (SSL) fallaría al inicio.</p>
</div>
</div>
<hr>
</section>
</section>
<section id="herramientas-de-admon-de-windows" class="level2" data-number="A.14">
<h2 data-number="A.14" class="anchored" data-anchor-id="herramientas-de-admon-de-windows"><span class="header-section-number">A.14</span> Herramientas de admon de Windows</h2>
<table class="table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Acceso Directo</th>
<th style="text-align: left;">Parámetro / Comando</th>
<th style="text-align: left;">Descripción</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Windows + R</strong></td>
<td style="text-align: left;"><code>%UserProfile%</code></td>
<td style="text-align: left;">Abre tu carpeta personal de usuario (donde se crea el archivo <code>.wslconfig</code>).</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Windows + R</strong></td>
<td style="text-align: left;"><code>cleanmgr</code></td>
<td style="text-align: left;">Abre el <strong>Liberador de espacio en disco</strong> para purgar basura del sistema.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Windows + R</strong></td>
<td style="text-align: left;"><code>taskmgr</code></td>
<td style="text-align: left;"><strong>[Ctrl + Shift + Esc]</strong> Abre el <strong>Administrador de Tareas</strong> para ver procesos.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Windows + R</strong></td>
<td style="text-align: left;"><code>resmon</code></td>
<td style="text-align: left;">Abre el <strong>Monitor de Recursos</strong> (ideal para ver el uso real de RAM y Swap).</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Windows + R</strong></td>
<td style="text-align: left;"><code>sysdm.cpl</code></td>
<td style="text-align: left;"><strong>[Win + Pausa]</strong> Propiedades del sistema (configuración de Memoria Virtual).</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Windows + R</strong></td>
<td style="text-align: left;"><code>%temp%</code></td>
<td style="text-align: left;">Abre la carpeta de <strong>Archivos temporales del usuario</strong> actual.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Windows + R</strong></td>
<td style="text-align: left;"><code>temp</code></td>
<td style="text-align: left;">Abre la carpeta de <strong>Archivos temporales del sistema</strong> (raíz).</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Windows + R</strong></td>
<td style="text-align: left;"><code>prefetch</code></td>
<td style="text-align: left;">Carpeta de precarga de Windows (caché que puedes vaciar para liberar espacio).</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Windows + R</strong></td>
<td style="text-align: left;"><code>diskmgmt.msc</code></td>
<td style="text-align: left;">Abre la <strong>Administración de discos</strong> (para vigilar tus unidades C: y D:).</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Windows + R</strong></td>
<td style="text-align: left;"><code>appdata</code></td>
<td style="text-align: left;">Acceso a carpetas de configuración de aplicaciones (Roaming/Local).</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Windows + R</strong></td>
<td style="text-align: left;"><code>cmd</code></td>
<td style="text-align: left;"><strong>[Win + X, luego C]</strong> Abre el Símbolo del Sistema (Terminal clásica).</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Windows + R</strong></td>
<td style="text-align: left;"><code>powershell</code></td>
<td style="text-align: left;"><strong>[Win + X, luego A]</strong> Abre PowerShell con permisos de administrador.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Windows + R</strong></td>
<td style="text-align: left;"><code>control</code></td>
<td style="text-align: left;">Abre el <strong>Panel de Control clásico</strong> de Windows.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Windows + R</strong></td>
<td style="text-align: left;"><code>msconfig</code></td>
<td style="text-align: left;">Configuración del sistema (gestión de servicios y arranque).</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Windows + R</strong></td>
<td style="text-align: left;"><code>ncpa.cpl</code></td>
<td style="text-align: left;">Panel de <strong>Conexiones de red</strong> (configuración de adaptadores e IPs).</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Nativo</strong></td>
<td style="text-align: left;"><strong>Win + E</strong></td>
<td style="text-align: left;">Abre instantáneamente el <strong>Explorador de Archivos</strong>.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Nativo</strong></td>
<td style="text-align: left;"><strong>Win + I</strong></td>
<td style="text-align: left;">Abre el panel de <strong>Configuración de Windows</strong> (Settings).</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Nativo</strong></td>
<td style="text-align: left;"><strong>Win + D</strong></td>
<td style="text-align: left;"><strong>Minimiza/Restaura todo</strong> para ir al Escritorio rápidamente.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Nativo</strong></td>
<td style="text-align: left;"><strong>Win + V</strong></td>
<td style="text-align: left;">Abre el <strong>Historial del Portapapeles</strong> (muy útil para copiar varios códigos).</td>
</tr>
</tbody>
</table>
<ul>
<li>Procesos de <strong>WSL2</strong> (Windows Subsystem for Linux 2): Docker y Vmmem</li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./71-presentacion_benchmark.html" class="pagination-link" aria-label="Benchmark geoespacial: cómo leer los resultados">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Benchmark geoespacial: cómo leer los resultados</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./92-errata.html" class="pagination-link" aria-label="Errata">
        <span class="nav-page-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Errata</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>